#pragma once

#include <ackermann_msgs/msg/ackermann_drive.hpp>
#include <chrono>
#include <costmap_converter_msgs/msg/obstacle_array_msg.hpp>
#include <limits>
#include <memory>
#include <nav2_teb_controller/obstacles/esdf.hpp>
#include <nav_msgs/msg/path.hpp>
#include <set>
#include <vector>

#include "nav2_costmap_2d/costmap_2d_ros.hpp"
#include "nav2_teb_controller/core/footprint.hpp"
#include "nav2_teb_controller/core/timed_elastic_band.hpp"
#include "nav2_teb_controller/homotopy/graph_search_interface.hpp"
#include "nav2_teb_controller/homotopy/h_signature.hpp"
#include "nav2_teb_controller/homotopy/teb_candidate.hpp"
#include "nav2_teb_controller/planner/optimal_planner.hpp"
#include "nav2_teb_controller/planner/planner_interface.hpp"
#include "nav2_teb_controller/teb_profiler.hpp"

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller {

/**
 * @brief HCP Wrapper: Finds N homotopy-distinct TEB trajectories
 *        and returns the best feasible one.
 *
 * Usage:
 *   HomotopyClassPlanner hcp(params, costmap);
 *   hcp.setGraphSearch(std::make_shared<VisibilityGraphSearch>());
 *   hcp.plan(path, twist);
 *   auto& best = hcp.getBestCandidate();
 */
class HomotopyClassPlanner : public PlannerInterface<TimedElasticBand> {
public:
  HomotopyClassPlanner(const teb_controller::Params &params, const Footprint &footprint,
                       nav2_costmap_2d::Costmap2DROS *costmap_ros);

  // ── PlannerBase Interface ──────────────────────────────────────────────
  bool plan(const nav_msgs::msg::Path &global_plan,
            const geometry_msgs::msg::Twist &start_vel) override;
  bool hasDiverged() override;
  void clear() override;

  // ── PlannerInterface<TEB> ─────────────────────────────────────────────
  [[nodiscard]] const TimedElasticBand &getTEB() const override;
  [[nodiscard]] double getCost() const override;
  void setFeedback(const ackermann_msgs::msg::AckermannDrive & /*feedback*/) override;
  void updateObstacleContainer(
      costmap_converter_msgs::msg::ObstacleArrayMsg::ConstSharedPtr /*obstacle_array*/) override;
  void setObstacleMap(const ObstacleMap2D *esdf) override;
  void setFixedGoal(bool fix) override;

  // ── HCP-specific ──────────────────────────────────────────────────────

  /** @brief Inject graph search strategy (Visibility/ProAStar) */
  void setGraphSearch(std::shared_ptr<GraphSearchInterface> graph_search);

  /** @brief Inject underlying TEB planner (DiscreteTEB/PolynomialTEB) */
  void setBasePlanner(std::shared_ptr<PlannerInterface<TimedElasticBand>> base_planner);

  /** @brief Get all TEB candidates (for visualization) */
  [[nodiscard]] const std::vector<TebCandidate::Ptr> &getCandidates() const { return candidates_; }

  /** @brief Index of the currently selected candidate (for best-highlighting) */
  [[nodiscard]] int bestCandidateIdx() const { return best_candidate_idx_; }

  /// Pure selection rule (exposed for unit testing): applies switch blocking, efficiency
  /// hysteresis (with anchor floor), and the progress guard against the previous best
  /// route; returns the winning candidate index (-1 if none).
  static int selectBestCandidateIndex(
      const std::vector<TebCandidate::Ptr> &candidates, bool has_prev_best,
      int prev_best_route_id, double prev_best_route_cost, bool switch_blocked,
      double selection_hysteresis, double prev_best_route_len = std::numeric_limits<double>::infinity(),
      double progress_slack = 0.0, double anchor_floor = 0.0);

  /** @brief Get best TEB candidate */
  [[nodiscard]] const TebCandidate &getBestCandidate() const;

  /** @brief Get the graph search (for visualization) */
  [[nodiscard]] const GraphSearchInterface *getGraphSearch() const { return graph_search_.get(); }

  /** @brief Number of graph-search executions (rate-limit observability, used by tests) */
  [[nodiscard]] uint64_t searchCount() const { return search_count_; }

  /**
   * @brief ESDF × footprint collision gate for an optimized band (public for unit
   *        testing). Candidates whose bands still intersect lethal cells after
   *        optimization are rejected regardless of their cost — obstacle-edge penalties
   *        alone don't guarantee footprint clearance (benchmark_test_19).
   * @return true if the band is collision-free within the lookahead
   */
  [[nodiscard]] bool passesFeasibilityGate(const TimedElasticBand &teb) const;

  /**
   * @brief Window containment gate (public for unit testing): rejects candidates whose
   *        band leaves the mapped ESDF window. Outside the window the ESDF clamps to the
   *        boundary value — unknown space reads as free and collision-free — so such
   *        "phantom" routes carry near-zero costs and win selection before vanishing in
   *        later rounds (the churn source in benchmark_test_20). Skipped entirely when
   *        the band's final pose lies outside the window itself: on long-haul legs every
   *        band ends beyond the local window, and rejecting them all would collapse HCP
   *        to its fallback.
   * @return true if the band stays within the mapped window (or containment doesn't apply)
   */
  [[nodiscard]] bool staysInWindow(const TimedElasticBand &teb) const;

private:
  /**
   * @brief Step 2: For each class, optimize a TEB
   *
   * @param robot_pose Live robot pose (from the controller's plan front) — seeded into
   *        every candidate band so pose(0)/heading always reflect the robot, not the
   *        possibly-stale graph-search start node.
   * @param goal_pose Mission goal pose — seeded into every candidate band's last vertex
   *        (heading included) and into the handed plan message.
   */
  void optimizeCandidates(const std::vector<GraphSearchResult> &classes,
                          const geometry_msgs::msg::Twist &start_vel, const PoseSE2 &robot_pose,
                          const PoseSE2 &goal_pose);

  /**
   * @brief Step 3: Select best feasible TEB by cost
   */
  [[nodiscard]] int selectBestCandidate() const;

  /**
   * @brief Update existing candidates (warm-start) or init new ones; pose 0 of each band
   *        is seeded with @p robot_pose (live robot pose + heading) and the last pose with
   *        @p goal_pose (mission goal pose + orientation) — the GVD polyline's terminal
   *        heading is connector-derived and would otherwise be pinned by fix_goal.
   */
  void updateCandidates(const std::vector<GraphSearchResult> &classes, const PoseSE2 &robot_pose,
                        const PoseSE2 &goal_pose);

  /**
   * @brief Prune candidates that have diverged or are too costly
   */
  void pruneCandidates();

  /**
   * @brief Grace-period continuity: when the previous best route's GVD class blinked out
   *        of the current search round but its RouteEntry still exists and was seen
   *        within hcp.route_grace_time, re-create a candidate from the route's last known
   *        polyline so it competes with a FRESH cost instead of the tick collapsing to
   *        cheapest-of-the-day (the ping-pong source in benchmark_test_19). Appends to
   *        @p classes.
   */
  void synthesizePrevRouteCandidate(std::vector<GraphSearchResult> &classes,
                                    const PoseSE2 &robot_pose, const PoseSE2 &goal_pose);

  /**
   * @brief Store a fallback candidate from the base planner's current TEB
   */
  void storeFallbackCandidate();

  /// One persistent route: identity + its optimizer. Matching is H-signature FIRST (the
  /// same corridor keeps its route across GVD re-extractions whose polyline geometry
  /// wobbles beyond kRouteMatchDist — the churn source behind benchmark_test_19's LRU
  /// evictions), geometric similarity second (survives sliding-window obstacle-set
  /// changes that do alter signatures). Warm starts persist as long as the route exists.
  struct RouteEntry {
    int route_id = -1;
    std::vector<PoseSE2> path;  ///< last known polyline (for geometric matching)
    HSignature h_signature;     ///< last known signature (for topological matching)
    std::shared_ptr<DiscreteTEBPlanner> planner;
    uint64_t last_seen_tick = 0;
  };

  /**
   * @brief Match a class against known routes — H-signature equality first, then
   *        geometric similarity (goal endpoint within reinit_dist + mean nearest-point
   *        distance below kRouteMatchDist) — or register it as a new route.
   *
   * Routes already present in @p consumed_ids are skipped during matching and the returned
   * id is inserted there — this enforces the PER-TICK INVARIANT that two candidates never
   * share one route/planner instance (parallel plan() calls on a single optimizer corrupt
   * its graph — field crash, benchmark_test_15).
   *
   * @return the route's id (existing or freshly created, with its own optimizer)
   */
  int matchOrCreateRoute(const std::vector<PoseSE2> &path, const HSignature &h_signature,
                         std::set<int> &consumed_ids);

  /**
   * @brief Optimizer owned by a route id (always exists after matchOrCreateRoute)
   */
  DiscreteTEBPlanner &plannerForRoute(int route_id);

  /**
   * @brief Drop stale routes (not seen recently)
   */
  void pruneRoutes();

  /**
   * @brief Re-run the graph search or reuse the cached classes per hcp.search_rate and
   *        endpoint movement. Appends usable classes to @p classes.
   * @return true if at least one class is available
   */
  bool refreshOrReuseClasses(const PoseSE2 &start, const PoseSE2 &goal,
                             std::vector<GraphSearchResult> &classes);

  /**
   * @brief A usable selection exists and was produced recently enough to keep serving it
   *        when a search/candidate round fails (avoids same-tick double solves).
   */
  [[nodiscard]] bool haveRecentCandidate() const;

  /**
   * @brief RCLCPP_WARN at most once per second, DEBUG otherwise
   */
  void warnThrottled(const char *message);

  const teb_controller::Params &params_;
  const Footprint &footprint_;
  nav2_costmap_2d::Costmap2DROS *costmap_ros_;

  std::shared_ptr<GraphSearchInterface> graph_search_;
  std::shared_ptr<PlannerInterface<TimedElasticBand>> base_planner_;

  std::vector<TebCandidate::Ptr> candidates_;
  int best_candidate_idx_ = -1;

  costmap_converter_msgs::msg::ObstacleArrayMsg::ConstSharedPtr obstacles_;
  const ObstacleMap2D *esdf_{nullptr};
  bool fixed_goal_{true};
  ackermann_msgs::msg::AckermannDrive last_ackermann_feedback_;

  std::vector<RouteEntry> routes_;
  int next_route_id_ = 0;
  uint64_t tick_{0};

  // Selection continuity: hysteresis + switch blocking + progress guard are anchored on
  // ROUTE identity (stable across obstacle-set changes), not on signatures. The anchor
  // cost is the EFFICIENCY category (see TebCandidate::efficiency_cost).
  int prev_best_route_id_ = -1;
  double prev_best_route_cost_ = std::numeric_limits<double>::infinity();
  /// Arc length of the previous best band — progress-guard anchor
  double prev_best_route_len_ = std::numeric_limits<double>::infinity();
  std::chrono::steady_clock::time_point last_switch_time_{};
  /// Last tick the previous best route was actually selected — anchors route_grace_time
  std::chrono::steady_clock::time_point last_prev_seen_time_{};
  bool has_prev_best_ = false;

  // Rate-limited graph search (hcp.search_rate): classes are cached between refreshes;
  // only the per-class TEB optimization runs every tick.
  std::vector<GraphSearchResult> cached_classes_;
  PoseSE2 last_search_start_{0.0, 0.0, 0.0};
  PoseSE2 last_search_goal_{0.0, 0.0, 0.0};
  std::chrono::steady_clock::time_point last_search_time_{};
  bool has_cached_search_ = false;
  uint64_t search_count_ = 0;
  /// Wall-clock duration of the previous plan() call — feeds the adaptive refresh
  /// interval so slow ticks push the next GVD/Yen refresh out by their own duration.
  std::chrono::duration<double> last_plan_elapsed_{0.0};

  std::chrono::steady_clock::time_point last_success_time_{};
  std::chrono::steady_clock::time_point last_fallback_warn_{};

  /// How long a previous successful selection may be served when a round fails [s]
  static constexpr double kRecentCandidateWindow = 0.3;
  static constexpr double kWarnInterval = 1.0;  ///< Fallback WARN throttle [s]
  /// Mean nearest-point distance for two polylines to count as the same route [m]
  static constexpr double kRouteMatchDist = 1.0;
  static constexpr size_t kMaxRoutes = 12;    ///< LRU bound on tracked routes
  static constexpr uint64_t kRouteTTL = 100;  ///< Ticks before an unused route drops
  /// Inward margin [m] for the window containment gate — topology sanity, not collision
  static constexpr double kWindowContainmentMargin = 0.5;
};

}  // namespace nav2_teb_controller
