#ifndef _EDGE_KINEMATICS_CAR_LIKE_H
#define EDGE_KINEMATICS_CAR_LIKE_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"

#include <cmath>
#include <angles/angles.h>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{

/**
 * @class EdgeKinematicsCarlike
 * @brief Edge defining the cost function for satisfying the non-holonomic kinematics of a carlike mobile robot.
 * 
 * The edge depends on two vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1} \f$ and minimizes a geometric interpretation
 * of the non-holonomic constraint: 
 *  - C. Rösmann et al.: Trajectory modification considering dynamic constraints of autonomous robots, ROBOTIK, 2012.
 * 
 * The definition is identically to the one of the differential drive robot.
 * Additionally, this edge incorporates a minimum turning radius that is required by carlike robots.
 * The turning radius is defined by \f$ r=v/omega \f$.
 * 
 * The \e weight can be set using setInformation(): Matrix element 1,1: (Choose a very high value: ~1000). \n
 * The second equation enforces a minimum turning radius.
 * The \e weight can be set using setInformation(): Matrix element 2,2. \n
 * The dimension of the error / cost vector is 3: the first component represents the nonholonomic constraint cost, 
 * the second one backward-drive cost and the third one the minimum turning radius
 * @see TebOptimalPlanner::AddEdgesKinematics, EdgeKinematicsDiffDrive
 * @remarks Bounding the turning radius from below is not affected by the penalty_epsilon parameter, 
 *          the user might add an extra margin to the min_turning_radius param.
 * @remarks Do not forget to call setTebConfig()
 */    
class EdgeKinematicsCarlike : public BaseTebBinaryEdge<2, double, VertexPose, VertexPose>
{
public:
  using BaseTebBinaryEdge<2, double, VertexPose, VertexPose>::linearizeOplus;

  
  /**
   * @brief Construct edge.
   */  
  EdgeKinematicsCarlike()
  {
      this->setMeasurement(0.);
  }
  
  /**
   * @brief Actual cost function
   */    
  void computeError() override
  {
    // read params
    const double turning_radius = params_->FollowPath.robot.min_turning_radius;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;
    
    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeKinematicsCarlike()");
    const auto* conf1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* conf2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    
    Eigen::Vector2d deltaS = conf2->position() - conf1->position();

    // non holonomic constraint
    _error[0] = std::abs( ( cos(conf1->theta())+cos(conf2->theta()) ) * deltaS[1] - ( sin(conf1->theta())+sin(conf2->theta()) ) * deltaS[0] );

    // limit minimum turning radius
    double angle_diff = angles::normalize_angle( conf2->theta() - conf1->theta() );
    if (angle_diff == 0)
      _error[1] = 0; // straight line motion
    else if (exact_arc_length) // use exact computation of the radius
      _error[1] = penaltyBoundFromBelow(fabs(deltaS.norm()/(2*sin(angle_diff/2))), turning_radius, 0.0);
    else
      _error[1] = penaltyBoundFromBelow(deltaS.norm() / fabs(angle_diff), turning_radius, 0.0); 
    // This edge is not affected by the epsilon parameter, the user might add an exra margin to the min_turning_radius parameter.
    
    // TEB_ASSERT_MSG(std::isfinite(_error[0]) && std::isfinite(_error[1]), "EdgeKinematicsCarlike::computeError() _error[0]=%f _error[1]=%f\n",_error[0],_error[1]);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   *
   * Row 0: non-holonomic constraint (same structure as EdgeKinematicsDiffDrive).
   * Row 1: minimum turning radius penalty.
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double turning_radius = params_->FollowPath.robot.min_turning_radius;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* conf1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* conf2 = dynamic_cast<const VertexPose*>(_vertices[1]);

    const Eigen::Vector2d deltaS = conf2->position() - conf1->position();
    const double dist = deltaS.norm();
    const double cos1 = std::cos(conf1->theta());
    const double cos2 = std::cos(conf2->theta());
    const double sin1 = std::sin(conf1->theta());
    const double sin2 = std::sin(conf2->theta());
    const double aux1 = sin1 + sin2;
    const double aux2 = cos1 + cos2;

    // --- Row 0: non-holonomic constraint e0 = |(c1+c2)dy - (s1+s2)dx| ---
    const double dev_nh_abs = std::copysign(1.0, aux2 * deltaS[1] - aux1 * deltaS[0]);

    // --- Row 1: turning radius penalty e1 = penaltyFromBelow(radius, r_min, 0) ---
    const double angle_diff = angles::normalize_angle(conf2->theta() - conf1->theta());

    _jacobianOplusXi.setZero();
    _jacobianOplusXj.setZero();

    // Row 0 blocks
    _jacobianOplusXi(0, 0) =  aux1 * dev_nh_abs;  // e0 x1
    _jacobianOplusXi(0, 1) = -aux2 * dev_nh_abs;  // e0 y1
    _jacobianOplusXi(0, 2) = (-sin1 * deltaS[1] - cos1 * deltaS[0]) * dev_nh_abs;  // e0 theta1
    _jacobianOplusXj(0, 0) = -aux1 * dev_nh_abs;  // e0 x2
    _jacobianOplusXj(0, 1) =  aux2 * dev_nh_abs;  // e0 y2
    _jacobianOplusXj(0, 2) = (-sin2 * deltaS[1] - cos2 * deltaS[0]) * dev_nh_abs;  // e0 theta2

    // Row 1 blocks: radius derivatives w.r.t. positions and headings
    if (std::abs(angle_diff) < 1e-12 || dist < 1e-12)
      return;  // e1 = 0 in the straight-line branch

    double radius = 0.0;
    double dr_ddist = 0.0;      // d radius / d dist
    double dr_dangle = 0.0;     // d radius / d angle_diff
    if (exact_arc_length)
    {
      const double s = std::sin(angle_diff / 2.0);
      const double g = 1.0 / (2.0 * std::abs(s));
      radius = dist * g;
      dr_ddist = g;
      // g'(t) = -sign(t) * cos(t/2) / (4 sin^2(t/2))
      dr_dangle = -dist * std::copysign(1.0, angle_diff) * std::cos(angle_diff / 2.0) /
                  (4.0 * s * s);
    }
    else
    {
      radius = dist / std::abs(angle_diff);
      dr_ddist = 1.0 / std::abs(angle_diff);
      dr_dangle = -dist * std::copysign(1.0, angle_diff) / (angle_diff * angle_diff);
    }

    const double dev_border =
        penaltyBoundFromBelowDerivative(radius, turning_radius, 0.0);

    // unit vector of deltaS
    const double ux = deltaS[0] / dist;
    const double uy = deltaS[1] / dist;
    // d(radius)/dp = -dr_ddist * unit,  d(radius)/dq = +dr_ddist * unit
    // d(angle_diff)/d theta1 = -1,  d(angle_diff)/d theta2 = +1
    _jacobianOplusXi(1, 0) = -dr_ddist * ux * dev_border;  // e1 x1
    _jacobianOplusXi(1, 1) = -dr_ddist * uy * dev_border;  // e1 y1
    _jacobianOplusXi(1, 2) = -dr_dangle * dev_border;      // e1 theta1
    _jacobianOplusXj(1, 0) =  dr_ddist * ux * dev_border;  // e1 x2
    _jacobianOplusXj(1, 1) =  dr_ddist * uy * dev_border;  // e1 y2
    _jacobianOplusXj(1, 2) =  dr_dangle * dev_border;      // e1 theta2
  }
#endif  // USE_ANALYTIC_JACOBI
  

  EIGEN_MAKE_ALIGNED_OPERATOR_NEW   
};

} // end namespace

#endif