#ifndef EDGE_SHORTEST_PATH_H_
#define EDGE_SHORTEST_PATH_H_

#include <float.h>

#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/vertex_pose.h"

#include <Eigen/Core>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{

/**
 * @class EdgeShortestPath
 * @brief Edge defining the cost function for minimizing the Euclidean distance between two consectuive poses.
 *
 * @see TebOptimalPlanner::AddEdgesShortestPath
 */
class EdgeShortestPath : public BaseTebBinaryEdge<1, double, VertexPose, VertexPose> {
public:
  using BaseTebBinaryEdge<1, double, VertexPose, VertexPose>::linearizeOplus;

  /**
   * @brief Construct edge.
   */
  EdgeShortestPath() { this->setMeasurement(0.); }

  /**
   * @brief Actual cost function
   */
  void computeError() override {
    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeShortestPath()");
    const auto *pose1 = static_cast<const VertexPose*>(_vertices[0]);
    const auto *pose2 = static_cast<const VertexPose*>(_vertices[1]);
    _error[0] = (pose2->position() - pose1->position()).norm();

    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeShortestPath::computeError() _error[0]=%f\n", _error[0]);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override {
    const auto *pose1 = static_cast<const VertexPose*>(_vertices[0]);
    const auto *pose2 = static_cast<const VertexPose*>(_vertices[1]);
    const Eigen::Vector2d delta = pose2->position() - pose1->position();
    const double dist = delta.norm();

    _jacobianOplusXi.setZero();
    _jacobianOplusXj.setZero();
    if (dist < 1e-12)
      return;  // non-differentiable point; zero gradient (matches g2o numeric behavior)
    const Eigen::Vector2d unit = delta / dist;
    _jacobianOplusXi(0, 0) = -unit.x();  // d e / d x1
    _jacobianOplusXi(0, 1) = -unit.y();  // d e / d y1
    _jacobianOplusXj(0, 0) =  unit.x();  // d e / d x2
    _jacobianOplusXj(0, 1) =  unit.y();  // d e / d y2
  }
#endif  // USE_ANALYTIC_JACOBI


  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif /* EDGE_SHORTEST_PATH_H_ */
