#ifndef EDGE_ESDF_OBSTACLE_H_
#define EDGE_ESDF_OBSTACLE_H_

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/core/footprint.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>
#include <g2o/core/robust_kernel_impl.h>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{
/// Dynamic-dimension ESDF obstacle edge.
/// Error dimension = footprint.circles().size() + 1 (set via resize()).
///
/// Error layout:
///   [0 .. N-1] → one component per footprint circle (obstacle penalty)
///   [N]        → inflation penalty at robot center
class EdgeESDFObstacle : public BaseTebUnaryEdge<-1, Eigen::VectorXd, VertexPose>
{
public:
  using BaseTebUnaryEdge<-1, Eigen::VectorXd, VertexPose>::linearizeOplus;

  EIGEN_MAKE_ALIGNED_OPERATOR_NEW

  /// Creates the edge with its own robust kernel (delta = 1.0). The kernel is
  /// owned by the edge: g2o's Edge dtor deletes it, and pooled edges keep their
  /// kernel for their whole lifetime — never share kernel objects across edges.
  EdgeESDFObstacle() { setRobustKernel(new g2o::RobustKernelHuber()); }

  /// Must be called before addEdge() — sets error dimension.
  void resize(int n_circles) {
    _dimension = n_circles + 1;   // circles + 1 inflation component
    _error.resize(_dimension);
    _error.setZero();
  }

  void computeError() override
  {
		const double min_dist = params_->FollowPath.obstacles.min_obstacle_dist;
    const double inflation_dist = params_->FollowPath.obstacles.inflation_dist;
    const double exp_scale = params_->FollowPath.obstacles.cost_exponent;
    // const double epsilon = params_->FollowPath.optimizer.penalty_epsilon;

    const auto* vp = static_cast<const VertexPose*>(this->_vertices[0]);

    const double px = vp->x();
    const double py = vp->y();
    const double ct = std::cos(vp->theta());
    const double st = std::sin(vp->theta());

    // ── Per-circle obstacle penalty ─────────────────────────────────────────
    const auto& circles = footprint_->circles();
    for (int i = 0; i < static_cast<int>(circles.size()); ++i) {
      const auto& c   = circles[i];
      const double wx = px + ct * c.offset.x() - st * c.offset.y();
      const double wy = py + st * c.offset.x() + ct * c.offset.y();

      const double dist = esdf_->queryDistance(wx, wy);
      const double threshold = min_dist + c.radius;

      _error[i] =  penaltyBoundFromBelow(dist, threshold, 0.0);

      if (dist <= threshold)
        _error[i] += std::expm1(exp_scale * (threshold - dist)) / exp_scale;
    }

    // ── Inflation penalty at robot center ────────────────────────────────────
    _error[_dimension - 1] = penaltyBoundFromBelow(esdf_->queryDistance(px, py), inflation_dist, 0.0);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   *
   * Row i: derivative of the per-circle obstacle penalty,
   * Row N: derivative of the center inflation penalty.
   * Uses the true (unnormalized) ESDF gradient.
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    const double min_dist = params_->FollowPath.obstacles.min_obstacle_dist;
    const double inflation_dist = params_->FollowPath.obstacles.inflation_dist;
    const double exp_scale = params_->FollowPath.obstacles.cost_exponent;

    const auto* vp = static_cast<const VertexPose*>(this->_vertices[0]);

    const double px = vp->x();
    const double py = vp->y();
    const double ct = std::cos(vp->theta());
    const double st = std::sin(vp->theta());

    _jacobianOplusXi.setZero();

    // ── Per-circle obstacle penalty ─────────────────────────────────────────
    const auto& circles = footprint_->circles();
    for (int i = 0; i < static_cast<int>(circles.size()); ++i) {
      const auto& c = circles[i];
      const double wx = px + ct * c.offset.x() - st * c.offset.y();
      const double wy = py + st * c.offset.x() + ct * c.offset.y();

      const auto esdf = esdf_->queryFull(wx, wy);
      const double dist = esdf.distance;
      const double threshold = min_dist + c.radius;
      if (dist > threshold)
        continue;  // penalty inactive

      // d(e_i)/d(dist) = -1 - exp(alpha * (threshold - dist))
      const double grad_mag = -1.0 - std::exp(exp_scale * (threshold - dist));
      const Eigen::Vector2d &grad = esdf.gradient;
      // d(w)/d(p) = I, d(w)/d(theta) = (-c.x*st - c.y*ct, c.x*ct - c.y*st)
      _jacobianOplusXi(i, 0) = grad_mag * grad.x();
      _jacobianOplusXi(i, 1) = grad_mag * grad.y();
      _jacobianOplusXi(i, 2) = grad_mag * (grad.x() * (-c.offset.x() * st - c.offset.y() * ct) +
                                           grad.y() * ( c.offset.x() * ct - c.offset.y() * st));
    }

    // ── Inflation penalty at robot center ───────────────────────────────────
    const auto center = esdf_->queryFull(px, py);
    if (center.distance < inflation_dist) {
      const Eigen::Vector2d &grad = center.gradient;
      _jacobianOplusXi(_dimension - 1, 0) = -grad.x();
      _jacobianOplusXi(_dimension - 1, 1) = -grad.y();
      // center offset is zero -> d(w)/d(theta) = 0
    }
  }
#endif  // USE_ANALYTIC_JACOBI

  void setObstacle(const ObstacleMap2D& esdf) { esdf_ = &esdf; }
  void setFootprint(const Footprint& fp) { footprint_ = &fp;   }

private:
  const ObstacleMap2D* esdf_{nullptr};
  const Footprint* footprint_{nullptr};
};

} // end namespace

#endif
