#ifndef EDGE_ACCELERATION_H_
#define EDGE_ACCELERATION_H_

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/edge_kinodynamics_helpers.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <geometry_msgs/msg/twist.hpp>
#include <angles/angles.h>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{

/**
 * @class EdgeAcceleration
 * @brief Edge defining the cost function for limiting the translational and rotational acceleration.
 * 
 * The edge depends on five vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \mathbf{s}_{ip2}, \Delta T_i, \Delta T_{ip1} \f$ and minimizes:
 * \f$ \min \textrm{penaltyInterval}( [a, omegadot } ]^T ) \cdot weight \f$. \n
 * \e a is calculated using the difference quotient (twice) and the position parts of all three poses \n
 * \e omegadot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi]. \n 
 * \e weight can be set using setInformation() \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval() \n
 * The dimension of the error / cost vector is 2: the first component represents the translational acceleration and
 * the second one the rotational acceleration.
 * @see TebOptimalPlanner::AddEdgesAcceleration
 * @see EdgeAccelerationStart
 * @see EdgeAccelerationGoal
 * @remarks Do not forget to call setTebConfig()
 * @remarks Refer to EdgeAccelerationStart() and EdgeAccelerationGoal() for defining boundary values!
 */    
class EdgeAcceleration : public BaseTebMultiEdge<2, double>
{
public:
  using BaseTebMultiEdge<2, double>::linearizeOplus;


  /**
   * @brief Construct edge.
   */ 
  EdgeAcceleration()
  {
    this->resize(5);
  }
    
  /**
   * @brief Actual cost function
   */   
  void computeError() override
  {
    // read params
    const double a_max_x = params_->FollowPath.robot.a_max_x;
    const double a_max_theta = params_->FollowPath.robot.a_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    // TEB_ASSERT_MSG(cfg_, "You must call setTebConfig on EdgeAcceleration()");
    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose3 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    // VELOCITY & ACCELERATION
    const Eigen::Vector2d diff1 = pose2->position() - pose1->position();
    const Eigen::Vector2d diff2 = pose3->position() - pose2->position();
        
    double dist1 = diff1.norm();
    double dist2 = diff2.norm();
    const double angle_diff1 = angles::normalize_angle(pose2->theta() - pose1->theta());
    const double angle_diff2 = angles::normalize_angle(pose3->theta() - pose2->theta());
    
    if (exact_arc_length) // use exact arc length instead of Euclidean approximation
    {
      if (angle_diff1 != 0)
      {
        const double radius =  dist1/(2*sin(angle_diff1/2));
        dist1 = fabs( angle_diff1 * radius ); // actual arg length!
      }
      if (angle_diff2 != 0)
      {
        const double radius =  dist2/(2*sin(angle_diff2/2));
        dist2 = fabs( angle_diff2 * radius ); // actual arg length!
      }
    }
    double vel1 = dist1 / dt1->dt();
    double vel2 = dist2 / dt2->dt();
    // consider directions
    // vel1 *= g2o::sign(diff1[0]*cos(pose1->theta()) + diff1[1]*sin(pose1->theta())); 
    // vel2 *= g2o::sign(diff2[0]*cos(pose2->theta()) + diff2[1]*sin(pose2->theta())); 
    vel1 *= fast_sigmoid( 100*(diff1.x()*cos(pose1->theta()) + diff1.y()*sin(pose1->theta())) ); 
    vel2 *= fast_sigmoid( 100*(diff2.x()*cos(pose2->theta()) + diff2.y()*sin(pose2->theta())) ); 
    const double acc_lin  = (vel2 - vel1)*2 / ( dt1->dt() + dt2->dt() );
    _error[0] = penaltyBoundToInterval(acc_lin, a_max_x, penalty_eps);
    
    // ANGULAR ACCELERATION
    const double omega1 = angle_diff1 / dt1->dt();
    const double omega2 = angle_diff2 / dt2->dt();
    const double acc_rot  = (omega2 - omega1)*2 / ( dt1->dt() + dt2->dt() );
    _error[1] = penaltyBoundToInterval(acc_rot, a_max_theta, penalty_eps);

    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeAcceleration::computeError() translational: _error[0]=%f\n",_error[0]);
    // TEB_ASSERT_MSG(std::isfinite(_error[1]), "EdgeAcceleration::computeError() rotational: _error[1]=%f\n",_error[1]);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   *
   * Row 0: translational acceleration, Row 1: rotational acceleration.
   * Includes the exact-arc-length variant and the sigmoid direction terms.
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double a_max_x = params_->FollowPath.robot.a_max_x;
    const double a_max_theta = params_->FollowPath.robot.a_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose3 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    const SegmentMotion seg1 = makeSegmentMotion(
      pose2->position() - pose1->position(), pose1->theta(), pose2->theta(),
      dt1->dt(), exact_arc_length);
    const SegmentMotion seg2 = makeSegmentMotion(
      pose3->position() - pose2->position(), pose2->theta(), pose3->theta(),
      dt2->dt(), exact_arc_length);
    const SigmoidTerm sig1 = makeSigmoidTerm(seg1.delta, seg1.cos_i, seg1.sin_i);
    const SigmoidTerm sig2 = makeSigmoidTerm(seg2.delta, seg2.cos_i, seg2.sin_i);

    const double vel1 = seg1.velRaw() * sig1.sigma;
    const double vel2 = seg2.velRaw() * sig2.sigma;
    const double omega1 = seg1.omega();
    const double omega2 = seg2.omega();

    const AccelPairGrads grads = makeAccelPairGrads(
      seg1, sig1, vel1, omega1, seg2, sig2, vel2, omega2);

    const double dev_lin = penaltyBoundToIntervalDerivative(
      grads.a_lin, a_max_x, penalty_eps);
    const double dev_rot = penaltyBoundToIntervalDerivative(
      grads.a_rot, a_max_theta, penalty_eps);

    _jacobianOplus[0].setZero();
    _jacobianOplus[1].setZero();
    _jacobianOplus[2].setZero();
    _jacobianOplus[3].setZero();
    _jacobianOplus[4].setZero();

    // conf1
    _jacobianOplus[0].block<1, 3>(0, 0) = dev_lin * (grads.lin_pose[0].transpose());
    _jacobianOplus[0].block<1, 3>(1, 0) = dev_rot * (grads.rot_pose[0].transpose());
    // conf2
    _jacobianOplus[1].block<1, 3>(0, 0) =
      dev_lin * (grads.lin_pose[1].transpose());
    _jacobianOplus[1].block<1, 3>(1, 0) =
      dev_rot * (grads.rot_pose[1].transpose());
    // conf3
    _jacobianOplus[2].block<1, 3>(0, 0) = dev_lin * (grads.lin_pose[2].transpose());
    _jacobianOplus[2].block<1, 3>(1, 0) = dev_rot * (grads.rot_pose[2].transpose());
    // deltaT1
    _jacobianOplus[3](0, 0) = dev_lin * grads.lin_dt[0];
    _jacobianOplus[3](1, 0) = dev_rot * grads.rot_dt[0];
    // deltaT2
    _jacobianOplus[4](0, 0) = dev_lin * grads.lin_dt[1];
    _jacobianOplus[4](1, 0) = dev_rot * grads.rot_dt[1];
  }
#endif  // USE_ANALYTIC_JACOBI

      

  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
   
};   
    
}; // end namespace

#endif /* EDGE_ACCELERATION_H_ */
