#ifndef EDGE_VELOCITY_H
#define EDGE_VELOCITY_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
/**
 * @class EdgeVelocity
 * @brief Edge defining the cost function for limiting the translational and rotational velocity.
 * 
 * The edge depends on three vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \Delta T_i \f$ and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [v,omega]^T ) \cdot weight \f$. \n
 * \e v is calculated using the difference quotient and the position parts of both poses. \n
 * \e omega is calculated using the difference quotient of both yaw angles followed by a normalization to [-pi, pi]. \n
 * \e weight can be set using setInformation(). \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval(). \n
 * The dimension of the error / cost vector is 2: the first component represents the translational velocity and
 * the second one the rotational velocity.
 * @see TebOptimalPlanner::AddEdgesVelocity
 * @remarks Do not forget to call setTebConfig()
 */  
class EdgeVelocity : public BaseTebMultiEdge<2, double>
{
public:
  using BaseTebMultiEdge<2, double>::linearizeOplus;

  
  /**
   * @brief Construct edge.
   */	      
  EdgeVelocity()
  {
    this->resize(3); // Since we derive from a g2o::BaseMultiEdge, set the desired number of vertices
  }
  
  /**
   * @brief Actual cost function
   */  
  void computeError() override
  {
    // read params
    const double v_max_x = params_->FollowPath.robot.v_max_x;
    const double v_max_x_backwards = params_->FollowPath.robot.v_max_x_backwards;
    const double v_max_theta = params_->FollowPath.robot.v_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    // TEB_ASSERT_MSG(params_.FollowPath."You must call setTebConfig on EdgeVelocity()");
    const auto* conf1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* conf2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* deltaT = dynamic_cast<const VertexTimeDiff*>(_vertices[2]);
    
    const Eigen::Vector2d deltaS = conf2->estimate().position() - conf1->estimate().position();
    
    double dist = deltaS.norm();
    const double angle_diff = angles::normalize_angle(conf2->theta() - conf1->theta());
    if (exact_arc_length && angle_diff != 0)
    {
        double radius =  dist/(2*sin(angle_diff/2));
        dist = fabs( angle_diff * radius ); // actual arg length!
    }
    double vel = dist / deltaT->estimate();
    
//     vel *= g2o::sign(deltaS[0]*cos(conf1->theta()) + deltaS[1]*sin(conf1->theta())); // consider direction
    vel *= fast_sigmoid( 100 * (deltaS.x()*cos(conf1->theta()) + deltaS.y()*sin(conf1->theta())) ); // consider direction
    
    const double omega = angle_diff / deltaT->estimate();
  
    _error[0] = penaltyBoundToInterval(vel, -v_max_x_backwards, v_max_x, penalty_eps);
    _error[1] = penaltyBoundToInterval(omega, v_max_theta, penalty_eps);

    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeVelocity::computeError() _error[0]=%f _error[1]=%f\n",_error[0],_error[1]);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   *
   * Full analytic Jacobian including the direction term (fast_sigmoid) and the
   * exact-arc-length variant of the translational velocity.
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double v_max_x = params_->FollowPath.robot.v_max_x;
    const double v_max_x_backwards = params_->FollowPath.robot.v_max_x_backwards;
    const double v_max_theta = params_->FollowPath.robot.v_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* conf1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* conf2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* deltaT = dynamic_cast<const VertexTimeDiff*>(_vertices[2]);

    const Eigen::Vector2d deltaS = conf2->position() - conf1->position();
    const double d0 = deltaS.norm();
    const double angle_diff = angles::normalize_angle(conf2->theta() - conf1->theta());
    const double dt = deltaT->estimate();
    const double cos1 = std::cos(conf1->theta());
    const double sin1 = std::sin(conf1->theta());

    // translational distance (optionally the exact arc length)
    double d = d0;
    double arc_factor = 1.0;    // d(arc)/d(d0) scaling
    double dh_da = 0.0;         // d(arc/d0)/d(angle_diff) for the exact variant
    if (exact_arc_length && angle_diff != 0.0 && d0 > 1e-12)
    {
      const double half = angle_diff / 2.0;
      const double s_half = std::sin(half);
      const double h = std::abs(angle_diff) / (2.0 * std::abs(s_half));
      d = d0 * h;
      arc_factor = h;
      dh_da = std::copysign(1.0, angle_diff) / (2.0 * std::abs(s_half)) -
              std::abs(angle_diff) * std::copysign(1.0, s_half) * std::cos(half) /
              (4.0 * s_half * s_half);
    }

    const double vel_raw = d / dt;
    // direction term (movement aligned with the robot heading)
    const double s_dir = deltaS.x() * cos1 + deltaS.y() * sin1;
    const double sigma = fast_sigmoid(100.0 * s_dir);
    const double sig_deriv = 100.0 / ((1.0 + 100.0 * std::abs(s_dir)) * (1.0 + 100.0 * std::abs(s_dir)));
    const double vel = vel_raw * sigma;
    const double omega = angle_diff / dt;

    const double dev_vel = penaltyBoundToIntervalDerivative(
      vel, -v_max_x_backwards, v_max_x, penalty_eps);
    const double dev_omega = penaltyBoundToIntervalDerivative(
      omega, v_max_theta, penalty_eps);

    _jacobianOplus[0].setZero();
    _jacobianOplus[1].setZero();
    _jacobianOplus[2].setZero();

    // --- Row 0: translational velocity ---
    const double pos_factor = d0 > 1e-12 ? arc_factor / (d0 * dt) : 0.0;
    const double extra_theta = exact_arc_length ? d0 * dh_da / dt : 0.0;

    // conf1 (p): d(vel)/dp = sigma * d(vel_raw)/dp + vel_raw * sig' * d(s_dir)/dp
    _jacobianOplus[0](0, 0) = dev_vel *
      (-sigma * deltaS.x() * pos_factor - vel_raw * sig_deriv * cos1);
    _jacobianOplus[0](0, 1) = dev_vel *
      (-sigma * deltaS.y() * pos_factor - vel_raw * sig_deriv * sin1);
    _jacobianOplus[0](0, 2) = dev_vel *
      (vel_raw * sig_deriv * (deltaS.y() * cos1 - deltaS.x() * sin1) -
       sigma * extra_theta);
    // conf2 (q)
    _jacobianOplus[1](0, 0) = dev_vel *
      (sigma * deltaS.x() * pos_factor + vel_raw * sig_deriv * cos1);
    _jacobianOplus[1](0, 1) = dev_vel *
      (sigma * deltaS.y() * pos_factor + vel_raw * sig_deriv * sin1);
    _jacobianOplus[1](0, 2) = dev_vel * sigma * extra_theta;
    // deltaT
    _jacobianOplus[2](0, 0) = dev_vel * (-vel / dt);

    // --- Row 1: rotational velocity ---
    _jacobianOplus[0](1, 2) = -dev_omega / dt;   // omega theta1
    _jacobianOplus[1](1, 2) =  dev_omega / dt;   // omega theta2
    _jacobianOplus[2](1, 0) = -omega * dev_omega / dt;  // omega deltaT
  }
#endif  // USE_ANALYTIC_JACOBI
 
  

  
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW

};

} // end namespace

#endif