#ifndef EDGE_ACCELERATION_START_H_
#define EDGE_ACCELERATION_START_H_

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/edge_kinodynamics_helpers.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <geometry_msgs/msg/twist.hpp>
#include <angles/angles.h>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{

/**
 * @class EdgeAccelerationStart
 * @brief Edge defining the cost function for limiting the translational and rotational acceleration at the beginning of the trajectory.
 *
 * The edge depends on three vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \Delta T_i \f$, an initial velocity defined by setInitialVelocity()
 * and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [a, omegadot ]^T ) \cdot weight \f$. \n
 * \e a is calculated using the difference quotient (twice) and the position parts of the poses. \n
 * \e omegadot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi].  \n
 * \e weight can be set using setInformation(). \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval(). \n
 * The dimension of the error / cost vector is 2: the first component represents the translational acceleration and
 * the second one the rotational acceleration.
 * @see TebOptimalPlanner::AddEdgesAcceleration
 * @see EdgeAcceleration
 * @see EdgeAccelerationGoal
 * @remarks Do not forget to call setTebConfig()
 * @remarks Refer to EdgeAccelerationGoal() for defining boundary values at the end of the trajectory!
 */      
class EdgeAccelerationStart : public BaseTebMultiEdge<2, const geometry_msgs::msg::Twist*>
{
public:
  using BaseTebMultiEdge<2, const geometry_msgs::msg::Twist*>::linearizeOplus;


  /**
   * @brief Construct edge.
   */	  
  EdgeAccelerationStart()
  {
    _measurement = nullptr;
    this->resize(3);
  }
  
  
  /**
   * @brief Actual cost function
   */   
  void computeError() override
  {
    // read params
    const double a_max_x = params_->FollowPath.robot.a_max_x;
    const double a_max_theta = params_->FollowPath.robot.a_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    // TEB_ASSERT_MSG(cfg_ && _measurement, "You must call setTebConfig() and setStartVelocity() on EdgeAccelerationStart()");
    const auto* pose1 = static_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = static_cast<const VertexPose*>(_vertices[1]);
    const auto* dt = static_cast<const VertexTimeDiff*>(_vertices[2]);

    // VELOCITY & ACCELERATION
    const Eigen::Vector2d diff = pose2->position() - pose1->position();
    double dist = diff.norm();
    const double angle_diff = angles::normalize_angle(pose2->theta() - pose1->theta());
    if (exact_arc_length && angle_diff != 0)
    {
        const double radius =  dist/(2*sin(angle_diff/2));
        dist = fabs( angle_diff * radius ); // actual arg length!
    }
    
    const double vel1 = _measurement->linear.x;
    double vel2 = dist / dt->dt();

    // consider directions
    //vel2 *= g2o::sign(diff[0]*cos(pose1->theta()) + diff[1]*sin(pose1->theta())); 
    vel2 *= fast_sigmoid( 100*(diff.x()*cos(pose1->theta()) + diff.y()*sin(pose1->theta())) ); 
    
    const double acc_lin  = (vel2 - vel1) / dt->dt();
    
    _error[0] = penaltyBoundToInterval(acc_lin, a_max_x, penalty_eps);
    
    // ANGULAR ACCELERATION
    const double omega1 = _measurement->angular.z;
    const double omega2 = angle_diff / dt->dt();
    const double acc_rot  = (omega2 - omega1) / dt->dt();
      
    _error[1] = penaltyBoundToInterval(acc_rot, a_max_theta, penalty_eps);

    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeAccelerationStart::computeError() translational: _error[0]=%f\n",_error[0]);
    // TEB_ASSERT_MSG(std::isfinite(_error[1]), "EdgeAccelerationStart::computeError() rotational: _error[1]=%f\n",_error[1]);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double a_max_x = params_->FollowPath.robot.a_max_x;
    const double a_max_theta = params_->FollowPath.robot.a_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* pose1 = static_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = static_cast<const VertexPose*>(_vertices[1]);
    const auto* dt = static_cast<const VertexTimeDiff*>(_vertices[2]);

    const SegmentMotion seg = makeSegmentMotion(
      pose2->position() - pose1->position(), pose1->theta(), pose2->theta(),
      dt->dt(), exact_arc_length);
    const SigmoidTerm sig = makeSigmoidTerm(seg.delta, seg.cos_i, seg.sin_i);

    const double vel1 = _measurement->linear.x;
    const double vel2 = seg.velRaw() * sig.sigma;
    const double omega1 = _measurement->angular.z;
    const double omega2 = seg.omega();
    const double acc_lin = (vel2 - vel1) / dt->dt();
    const double acc_rot = (omega2 - omega1) / dt->dt();

    const double dev_lin = penaltyBoundToIntervalDerivative(acc_lin, a_max_x, penalty_eps);
    const double dev_rot = penaltyBoundToIntervalDerivative(acc_rot, a_max_theta, penalty_eps);

    const Eigen::Vector2d u = seg.unit();
    const double dist = seg.d0 * seg.arc;
    const double dvel2_dtheta1 =
      seg.velRaw() * sig.deriv * sig.rot1 - sig.sigma * seg.d0 * seg.dh_da / dt->dt();
    const double dvel2_dtheta2 = sig.sigma * seg.d0 * seg.dh_da / dt->dt();

    _jacobianOplus[0].setZero();
    _jacobianOplus[1].setZero();
    _jacobianOplus[2].setZero();

    // conf1
    _jacobianOplus[0](0, 0) = dev_lin * (-sig.sigma * seg.arc * u.x() - dist * sig.deriv * seg.cos_i) / (dt->dt() * dt->dt());
    _jacobianOplus[0](0, 1) = dev_lin * (-sig.sigma * seg.arc * u.y() - dist * sig.deriv * seg.sin_i) / (dt->dt() * dt->dt());
    _jacobianOplus[0](0, 2) = dev_lin * (dvel2_dtheta1 / dt->dt());
    _jacobianOplus[0](1, 2) = dev_rot * (-1.0 / (dt->dt() * dt->dt()));
    // conf2
    _jacobianOplus[1](0, 0) = dev_lin * (sig.sigma * seg.arc * u.x() + dist * sig.deriv * seg.cos_i) / (dt->dt() * dt->dt());
    _jacobianOplus[1](0, 1) = dev_lin * (sig.sigma * seg.arc * u.y() + dist * sig.deriv * seg.sin_i) / (dt->dt() * dt->dt());
    _jacobianOplus[1](0, 2) = dev_lin * (dvel2_dtheta2 / dt->dt());
    _jacobianOplus[1](1, 2) = dev_rot * (1.0 / (dt->dt() * dt->dt()));
    // deltaT
    _jacobianOplus[2](0, 0) = dev_lin * (-acc_lin / dt->dt() - vel2 / (dt->dt() * dt->dt()));
    _jacobianOplus[2](1, 0) = dev_rot * (-acc_rot / dt->dt() - omega2 / (dt->dt() * dt->dt()));
  }
#endif  // USE_ANALYTIC_JACOBI
  
  /**
   * @brief Set the initial velocity that is taken into account for calculating the acceleration
   * @param vel_start twist message containing the translational and rotational velocity
   */    
  void setInitialVelocity(const geometry_msgs::msg::Twist& vel_start)
  {
    _measurement = &vel_start;
  }
  
      
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

}; // end namespace

#endif /* EDGE_ACCELERATION_START_H_ */