#ifndef EDGE_STEERING_RATE_H
#define EDGE_STEERING_RATE_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
/**
 * @class EdgeSteeringRate
 * @brief Edge defining the cost function for limiting the steering rate w.r.t. the current wheelbase parameter
 *
 * The edge depends on four vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \mathbf{s}_{ip2} \Delta T_i \f$ .
 * @remarks This edge requires the TebConfig::Robot::whelbase parameter to be set.
 * @remarks Do not forget to call setTebConfig()
 */ 
class EdgeSteeringRate : public BaseTebMultiEdge<1, double>
{
public:
  using BaseTebMultiEdge<1, double>::linearizeOplus;


  /**
   * @brief Construct edge.
   */	      
  EdgeSteeringRate()
  {
    this->resize(5); // Since we derive from a g2o::BaseMultiEdge, set the desired number of vertices
  }

  /**
   * @brief Actual cost function
   */  
  void computeError() override
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;
    const double steering_rate_max = params_->FollowPath.robot.steering_rate_max;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* conf1 = static_cast<const VertexPose*>(_vertices[0]);
    const auto* conf2 = static_cast<const VertexPose*>(_vertices[1]);
    const auto* conf3 = static_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = static_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = static_cast<const VertexTimeDiff*>(_vertices[4]);

    Eigen::Vector2d delta_s1 = conf2->estimate().position() - conf1->estimate().position();
    Eigen::Vector2d delta_s2 = conf3->estimate().position() - conf2->estimate().position();
    double dist1 = delta_s1.norm();
    double dist2 = delta_s2.norm();
    double angle_diff1 = angles::normalize_angle( conf2->theta() - conf1->theta() );
    double angle_diff2 = angles::normalize_angle( conf3->theta() - conf2->theta() );

    if (dist1 < 1e-12 || dist2 < 1e-12)
    {
        _error[0] = 0.0;
        return;
    }

    const double sign1 = (delta_s1.dot(Eigen::Vector2d(std::cos(conf1->theta()), std::sin(conf1->theta()))) >= 0.0) ? 1.0 : -1.0;
    const double sign2 = (delta_s2.dot(Eigen::Vector2d(std::cos(conf2->theta()), std::sin(conf2->theta()))) >= 0.0) ? 1.0 : -1.0;

    double phi1 = exact_arc_length
        ? std::atan((wheelbase / dist1) * 2.0 * std::sin(angle_diff1 / 2.0))
        : std::atan((wheelbase / dist1) * angle_diff1);
    phi1 *= sign1;

    double phi2 = exact_arc_length
        ? std::atan((wheelbase / dist2) * 2.0 * std::sin(angle_diff2 / 2.0))
        : std::atan((wheelbase / dist2) * angle_diff2);
    phi2 *= sign2;

    const double avg_dt = 0.5 * (dt1->dt() + dt2->dt());
    const double steer_rate = (avg_dt > 1e-12) ? (phi2 - phi1) / avg_dt : 0.0;

    _error[0] = penaltyBoundToInterval(steer_rate, steering_rate_max, penalty_eps);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   *
   * The direction sign is treated as locally constant (the edge itself uses a
   * hard sign, which is non-differentiable at the sign flip).
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;
    const double steering_rate_max = params_->FollowPath.robot.steering_rate_max;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* conf1 = static_cast<const VertexPose*>(_vertices[0]);
    const auto* conf2 = static_cast<const VertexPose*>(_vertices[1]);
    const auto* conf3 = static_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = static_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = static_cast<const VertexTimeDiff*>(_vertices[4]);

    const Eigen::Vector2d delta_s1 = conf2->position() - conf1->position();
    const Eigen::Vector2d delta_s2 = conf3->position() - conf2->position();
    const double dist1 = delta_s1.norm();
    const double dist2 = delta_s2.norm();
    const double angle_diff1 = angles::normalize_angle(conf2->theta() - conf1->theta());
    const double angle_diff2 = angles::normalize_angle(conf3->theta() - conf2->theta());

    _jacobianOplus[0].setZero();
    _jacobianOplus[1].setZero();
    _jacobianOplus[2].setZero();
    _jacobianOplus[3].setZero();
    _jacobianOplus[4].setZero();
    if (dist1 < 1e-12 || dist2 < 1e-12)
      return;  // error is identically zero

    const double sign1 =
      (delta_s1.dot(Eigen::Vector2d(std::cos(conf1->theta()), std::sin(conf1->theta()))) >= 0.0)
      ? 1.0 : -1.0;
    const double sign2 =
      (delta_s2.dot(Eigen::Vector2d(std::cos(conf2->theta()), std::sin(conf2->theta()))) >= 0.0)
      ? 1.0 : -1.0;

    // phi = sign * atan(k), k = wheelbase/dist * g(angle_diff)
    // d(phi)/d(dist) = -sign * k / (dist * (1 + k^2))
    // d(phi)/d(angle_diff) = sign * wheelbase/dist * g' / (1 + k^2)
    const double k1 = (wheelbase / dist1) *
      (exact_arc_length ? 2.0 * std::sin(angle_diff1 / 2.0) : angle_diff1);
    const double k2 = (wheelbase / dist2) *
      (exact_arc_length ? 2.0 * std::sin(angle_diff2 / 2.0) : angle_diff2);
    const double g1p = exact_arc_length ? std::cos(angle_diff1 / 2.0) : 1.0;
    const double g2p = exact_arc_length ? std::cos(angle_diff2 / 2.0) : 1.0;
    const double phi1_d_dist = -sign1 * k1 / (dist1 * (1.0 + k1 * k1));
    const double phi2_d_dist = -sign2 * k2 / (dist2 * (1.0 + k2 * k2));
    const double phi1_d_angle = sign1 * (wheelbase / dist1) * g1p / (1.0 + k1 * k1);
    const double phi2_d_angle = sign2 * (wheelbase / dist2) * g2p / (1.0 + k2 * k2);

    const double avg_dt = 0.5 * (dt1->dt() + dt2->dt());
    const double inv_avg_dt = 1.0 / avg_dt;

    const Eigen::Vector2d u1 = delta_s1 / dist1;
    const Eigen::Vector2d u2 = delta_s2 / dist2;

    const double phi1 = sign1 * std::atan(k1);
    const double phi2 = sign2 * std::atan(k2);
    const double steer_rate = (phi2 - phi1) * inv_avg_dt;
    const double dev = penaltyBoundToIntervalDerivative(
      steer_rate, steering_rate_max, penalty_eps);

    // d(steer_rate) = (d(phi2) - d(phi1)) / avg_dt
    // conf1
    _jacobianOplus[0](0, 0) = dev * (-inv_avg_dt * phi1_d_dist * (-u1.x()));
    _jacobianOplus[0](0, 1) = dev * (-inv_avg_dt * phi1_d_dist * (-u1.y()));
    _jacobianOplus[0](0, 2) = dev * (-inv_avg_dt * (-phi1_d_angle));
    // conf2
    _jacobianOplus[1](0, 0) = dev * inv_avg_dt * (phi2_d_dist * (-u2.x()) - phi1_d_dist * u1.x());
    _jacobianOplus[1](0, 1) = dev * inv_avg_dt * (phi2_d_dist * (-u2.y()) - phi1_d_dist * u1.y());
    _jacobianOplus[1](0, 2) = dev * inv_avg_dt * (-phi2_d_angle - phi1_d_angle);
    // conf3
    _jacobianOplus[2](0, 0) = dev * inv_avg_dt * phi2_d_dist * u2.x();
    _jacobianOplus[2](0, 1) = dev * inv_avg_dt * phi2_d_dist * u2.y();
    _jacobianOplus[2](0, 2) = dev * inv_avg_dt * phi2_d_angle;
    // deltaT1 / deltaT2 (d avg_dt / dt = 1/2)
    _jacobianOplus[3](0, 0) = dev * (-0.5 * inv_avg_dt * steer_rate);
    _jacobianOplus[4](0, 0) = dev * (-0.5 * inv_avg_dt * steer_rate);
  }
#endif  // USE_ANALYTIC_JACOBI


  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif