#ifndef EDGE_G3_CONTINUITY_H
#define EDGE_G3_CONTINUITY_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
/**
 * @class EdgeG3Continuity
 * @brief Edge for penalizing the curvature rate to approximate G3 continuity.
 *
 * This edge minimizes the change in curvature over three consecutive poses.
 * It is specifically designed to handle 360-degree steering capabilities by
 * calculating the error in the steering angle space and normalizing the difference.
 * This version correctly handles the relationship between curvature and steering
 * angle for both forward and backward motion.
 *
 * The underlying cost function is:
 *   ( normalize_angle(phi_2 - phi_1) )^2
 * where phi_1 and phi_2 are the steering angles corresponding to the
 * curvatures of the two segments, correctly calculated for the driving direction.
 *
 * @see VertexPose
 */
class EdgeG3Continuity : public BaseTebMultiEdge<1, std::nullptr_t>
{
public:
  using BaseTebMultiEdge<1, std::nullptr_t>::linearizeOplus;

  /**
   * @brief Construct edge.
   */
  EdgeG3Continuity()
  {
    this->resize(5);
  }

  /**
   * @brief Actual cost function
   */
  void computeError() override
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;
    const double steering_rate_max = params_->FollowPath.robot.steering_rate_max;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;

    const auto* pose_prev = static_cast<const VertexPose*>(_vertices[0]);
    const auto* pose_curr = static_cast<const VertexPose*>(_vertices[1]);
    const auto* pose_next = static_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = static_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = static_cast<const VertexTimeDiff*>(_vertices[4]);

    // Approximate path length between poses
    const Eigen::Vector2d diff1 = pose_curr->position() - pose_prev->position();
    const double dist1 = diff1.norm();
    const Eigen::Vector2d diff2 = pose_next->position() - pose_curr->position();
    const double dist2 = diff2.norm();

    // Check for small distances to avoid division by zero
    if (dist1 < 1e-4 || dist2 < 1e-4)
    {
      _error[0] = 0.0;
      return;
    }

    // --- Curvature Calculation ---
    const double delta_theta1 = angles::normalize_angle(pose_curr->theta() - pose_prev->theta());
    const double delta_theta2 = angles::normalize_angle(pose_next->theta() - pose_curr->theta());
    const double dir1 = diff1.x() * std::cos(pose_prev->theta()) + diff1.y() * std::sin(pose_prev->theta());
    const double dir2 = diff2.x() * std::cos(pose_curr->theta()) + diff2.y() * std::sin(pose_curr->theta());
    const double kappa1 = (dir1 >= 0) ? (delta_theta1 / dist1) : (-delta_theta1 / dist1);
    const double kappa2 = (dir2 >= 0) ? (delta_theta2 / dist2) : (-delta_theta2 / dist2);

    // 1. Konvertiere die Krümmung (kappa) in den Lenkwinkel (phi).
    //    BEACHTE: Bei Rückwärtsfahrt kehrt sich die Beziehung um!
    //    Forward:  phi = atan(kappa * L)
    //    Backward: phi = atan(-kappa * L)

    const double phi1 = (dir1 >= 0) ? atan(kappa1 * wheelbase) : atan(-kappa1 * wheelbase);
    const double phi2 = (dir2 >= 0) ? atan(kappa2 * wheelbase) : atan(-kappa2 * wheelbase);

    // 2. Berechne die normalisierte Differenz der Lenkwinkel.
    //    Dieser Schritt bleibt gleich und behandelt die 360°-Natur korrekt.
    const double phi2_ = unwrapSteeringAngle(phi2, phi1);
    // const double delta_phi = angles::normalize_angle(phi2 - phi1);
    const double delta_phi  = phi2_ - phi1;  // kein normalize_angle nach unwrap!

    // // --- Steuerrate: delta_phi / mittlere Zeit der beiden Segmente
    const double avg_dt     = 0.5 * (dt1->dt() + dt2->dt());
    const double steer_rate = (avg_dt > 1e-6) ? (std::abs(delta_phi) / avg_dt) : 0.0;

    // 3. Der Fehler ist diese normalisierte Winkeldifferenz.
    // _error[0] = delta_phi;
    _error[0] = penaltyBoundFromBelow(steering_rate_max, steer_rate, penalty_eps);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   *
   * Note: phi_i = atan(kappa_i * L) equals atan(delta_theta_i * L / dist_i)
   * for both driving directions (the sign flips cancel), so the Jacobian is
   * independent of the direction. The unwrap branch is treated as locally
   * constant.
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double wheelbase = params_->FollowPath.robot.wheelbase;
    const double steering_rate_max = params_->FollowPath.robot.steering_rate_max;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;

    const auto* pose_prev = static_cast<const VertexPose*>(_vertices[0]);
    const auto* pose_curr = static_cast<const VertexPose*>(_vertices[1]);
    const auto* pose_next = static_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = static_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = static_cast<const VertexTimeDiff*>(_vertices[4]);

    const Eigen::Vector2d diff1 = pose_curr->position() - pose_prev->position();
    const double dist1 = diff1.norm();
    const Eigen::Vector2d diff2 = pose_next->position() - pose_curr->position();
    const double dist2 = diff2.norm();

    for (int i = 0; i < 5; ++i)
      _jacobianOplus[i].setZero();
    if (dist1 < 1e-4 || dist2 < 1e-4)
      return;  // error is identically zero

    const double a1 = angles::normalize_angle(pose_curr->theta() - pose_prev->theta());
    const double a2 = angles::normalize_angle(pose_next->theta() - pose_curr->theta());

    // phi_i = atan(L * a_i / dist_i)
    const double k1 = wheelbase * a1 / dist1;
    const double k2 = wheelbase * a2 / dist2;
    const double dphi1_d_dist = -k1 / (dist1 * (1.0 + k1 * k1));
    const double dphi2_d_dist = -k2 / (dist2 * (1.0 + k2 * k2));
    const double dphi1_d_angle = wheelbase / (dist1 * (1.0 + k1 * k1));
    const double dphi2_d_angle = wheelbase / (dist2 * (1.0 + k2 * k2));

    const double phi1 = std::atan(k1);
    const double phi2 = std::atan(k2);
    const double phi2_ = unwrapSteeringAngle(phi2, phi1);
    const double delta_phi = phi2_ - phi1;

    const double avg_dt = 0.5 * (dt1->dt() + dt2->dt());
    const double steer_rate = std::abs(delta_phi) / avg_dt;
    const double dev = -penaltyBoundFromBelowDerivative(
      steering_rate_max, steer_rate, penalty_eps);
    const double sign_delta = delta_phi > 0.0 ? 1.0 : (delta_phi < 0.0 ? -1.0 : 0.0);
    const double inv_avg_dt = 1.0 / avg_dt;

    const Eigen::Vector2d u1 = diff1 / dist1;
    const Eigen::Vector2d u2 = diff2 / dist2;

    // d(steer_rate)/d(phi_i) = sign * (+/-1) / avg_dt (delta_phi = phi2_ - phi1)
    // pose_prev: only via phi1 (position and heading)
    _jacobianOplus[0](0, 0) = dev * sign_delta * inv_avg_dt * dphi1_d_dist * u1.x();
    _jacobianOplus[0](0, 1) = dev * sign_delta * inv_avg_dt * dphi1_d_dist * u1.y();
    _jacobianOplus[0](0, 2) = dev * sign_delta * inv_avg_dt * dphi1_d_angle;
    // pose_curr
    _jacobianOplus[1](0, 0) = dev * sign_delta * inv_avg_dt *
      (-dphi1_d_dist * u1.x() - dphi2_d_dist * u2.x());
    _jacobianOplus[1](0, 1) = dev * sign_delta * inv_avg_dt *
      (-dphi1_d_dist * u1.y() - dphi2_d_dist * u2.y());
    _jacobianOplus[1](0, 2) = dev * sign_delta * inv_avg_dt *
      (-(dphi1_d_angle + dphi2_d_angle));
    // pose_next
    _jacobianOplus[2](0, 0) = dev * sign_delta * inv_avg_dt * dphi2_d_dist * u2.x();
    _jacobianOplus[2](0, 1) = dev * sign_delta * inv_avg_dt * dphi2_d_dist * u2.y();
    _jacobianOplus[2](0, 2) = dev * sign_delta * inv_avg_dt * dphi2_d_angle;
    // deltaT1 / deltaT2
    _jacobianOplus[3](0, 0) = dev * (-0.5 * inv_avg_dt * steer_rate);
    _jacobianOplus[4](0, 0) = dev * (-0.5 * inv_avg_dt * steer_rate);
  }
#endif  // USE_ANALYTIC_JACOBI


  /// Pick the equivalent angle (φ or φ±π) closest to reference
  static double unwrapSteeringAngle(double phi, double reference)
  {
    const double d0 = std::abs(angles::normalize_angle(phi - reference));
    const double d1 = std::abs(angles::normalize_angle(phi + M_PI - reference));
    const double d2 = std::abs(angles::normalize_angle(phi - M_PI - reference));
    if (d1 < d0 && d1 < d2) return phi + M_PI;
    if (d2 < d0 && d2 < d1) return phi - M_PI;
    return phi;
  }
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif