#ifndef EDGE_ACCELERATION_HOLONOMIC_START_H_
#define EDGE_ACCELERATION_HOLONOMIC_START_H_

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <angles/angles.h>
#include <exception>

#include <geometry_msgs/msg/twist.hpp>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{
/**
 * @class EdgeAccelerationHolonomicStart
 * @brief Edge defining the cost function for limiting the translational and rotational acceleration at the beginning of the trajectory.
 *
 * The edge depends on three vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \Delta T_i \f$, an initial velocity defined by setInitialVelocity()
 * and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [ax, ay, omegadot ]^T ) \cdot weight \f$. \n
 * \e ax is calculated using the difference quotient (twice) and the x-position parts of the poses. \n
 * \e ay is calculated using the difference quotient (twice) and the y-position parts of the poses. \n
 * \e omegadot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi].  \n
 * \e weight can be set using setInformation(). \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval(). \n
 * The dimension of the error / cost vector is 3: the first component represents the translational acceleration,
 * the second one the strafing acceleration and the third one the rotational acceleration.
 * @see TebOptimalPlanner::AddEdgesAcceleration
 * @see EdgeAccelerationHolonomic
 * @see EdgeAccelerationHolonomicGoal
 * @remarks Do not forget to call setTebConfig()
 * @remarks Refer to EdgeAccelerationHolonomicGoal() for defining boundary values at the end of the trajectory!
 */      
class EdgeAccelerationHolonomicStart : public BaseTebMultiEdge<3, const geometry_msgs::msg::Twist*>
{
public:
  using BaseTebMultiEdge<3, const geometry_msgs::msg::Twist*>::linearizeOplus;

  /**
   * @brief Construct edge.
   */   
  EdgeAccelerationHolonomicStart()
  {
    this->resize(3);
    _measurement = nullptr;
  }
  /**
   * @brief Actual cost function
   */   
  void computeError() override
  {
    // read params
    const double a_max_x = params_->FollowPath.robot.a_max_x;
    const double a_max_y = params_->FollowPath.robot.a_max_y;
    const double a_max_theta = params_->FollowPath.robot.a_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;

    // TEB_ASSERT_MSG(cfg_ && _measurement, "You must call setTebConfig() and setStartVelocity() on EdgeAccelerationStart()");
    const auto* pose1 = static_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = static_cast<const VertexPose*>(_vertices[1]);
    const auto* dt = static_cast<const VertexTimeDiff*>(_vertices[2]);

    // VELOCITY & ACCELERATION
    Eigen::Vector2d diff = pose2->position() - pose1->position();
            
    double cos_theta1 = std::cos(pose1->theta());
    double sin_theta1 = std::sin(pose1->theta()); 
    
    // transform pose2 into robot frame pose1 (inverse 2d rotation matrix)
    double p1_dx =  cos_theta1*diff.x() + sin_theta1*diff.y();
    double p1_dy = -sin_theta1*diff.x() + cos_theta1*diff.y();
    
    double vel1_x = _measurement->linear.x;
    double vel1_y = _measurement->linear.y;
    double vel2_x = p1_dx / dt->dt();
    double vel2_y = p1_dy / dt->dt();

    double acc_lin_x  = (vel2_x - vel1_x) / dt->dt();
    double acc_lin_y  = (vel2_y - vel1_y) / dt->dt();
    
    _error[0] = penaltyBoundToInterval(acc_lin_x, a_max_x, penalty_eps);
    _error[1] = penaltyBoundToInterval(acc_lin_y, a_max_y, penalty_eps);
    
    // ANGULAR ACCELERATION
    double omega1 = _measurement->angular.z;
    double omega2 = angles::normalize_angle(pose2->theta() - pose1->theta()) / dt->dt();
    double acc_rot  = (omega2 - omega1) / dt->dt();
      
    _error[2] = penaltyBoundToInterval(acc_rot, a_max_theta, penalty_eps);

    // TEB_ASSERT_MSG(std::isfinite(_error[0]), "EdgeAccelerationStart::computeError() translational: _error[0]=%f\n",_error[0]);
    // TEB_ASSERT_MSG(std::isfinite(_error[1]), "EdgeAccelerationStart::computeError() strafing: _error[1]=%f\n",_error[1]);
    // TEB_ASSERT_MSG(std::isfinite(_error[2]), "EdgeAccelerationStart::computeError() rotational: _error[2]=%f\n",_error[2]);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double a_max_x = params_->FollowPath.robot.a_max_x;
    const double a_max_y = params_->FollowPath.robot.a_max_y;
    const double a_max_theta = params_->FollowPath.robot.a_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;

    const auto* pose1 = static_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = static_cast<const VertexPose*>(_vertices[1]);
    const auto* dt = static_cast<const VertexTimeDiff*>(_vertices[2]);

    const Eigen::Vector2d diff = pose2->position() - pose1->position();
    const double cos1 = std::cos(pose1->theta());
    const double sin1 = std::sin(pose1->theta());

    // inverse 2d rotation matrix applied to the segment difference
    const Eigen::Matrix2d rot1 = (Eigen::Matrix2d() << cos1, sin1, -sin1, cos1).finished();
    const Eigen::Vector2d r1 = rot1 * diff;

    const double vel1_x = _measurement->linear.x;
    const double vel1_y = _measurement->linear.y;
    const Eigen::Vector2d vel2 = r1 / dt->dt();
    const double omega1 = _measurement->angular.z;
    const double omega2 = angles::normalize_angle(pose2->theta() - pose1->theta()) / dt->dt();
    const Eigen::Vector2d acc = (vel2 - Eigen::Vector2d(vel1_x, vel1_y)) / dt->dt();
    const double acc_rot = (omega2 - omega1) / dt->dt();

    const double dev_x = penaltyBoundToIntervalDerivative(acc.x(), a_max_x, penalty_eps);
    const double dev_y = penaltyBoundToIntervalDerivative(acc.y(), a_max_y, penalty_eps);
    const double dev_rot = penaltyBoundToIntervalDerivative(acc_rot, a_max_theta, penalty_eps);

    // d(r1)/d theta1 = (r1.y, -r1.x)
    const Eigen::Vector2d drot1(r1.y(), -r1.x());
    const double inv_dt2 = 1.0 / (dt->dt() * dt->dt());

    _jacobianOplus[0].setZero();
    _jacobianOplus[1].setZero();
    _jacobianOplus[2].setZero();

    // conf1
    _jacobianOplus[0](0, 0) = dev_x * (-rot1(0, 0) * inv_dt2);
    _jacobianOplus[0](0, 1) = dev_x * (-rot1(0, 1) * inv_dt2);
    _jacobianOplus[0](1, 0) = dev_y * (-rot1(1, 0) * inv_dt2);
    _jacobianOplus[0](1, 1) = dev_y * (-rot1(1, 1) * inv_dt2);
    _jacobianOplus[0](0, 2) = dev_x * (drot1.x() * inv_dt2);
    _jacobianOplus[0](1, 2) = dev_y * (drot1.y() * inv_dt2);
    _jacobianOplus[0](2, 2) = dev_rot * (-inv_dt2);
    // conf2
    _jacobianOplus[1](0, 0) = dev_x * (rot1(0, 0) * inv_dt2);
    _jacobianOplus[1](0, 1) = dev_x * (rot1(0, 1) * inv_dt2);
    _jacobianOplus[1](1, 0) = dev_y * (rot1(1, 0) * inv_dt2);
    _jacobianOplus[1](1, 1) = dev_y * (rot1(1, 1) * inv_dt2);
    _jacobianOplus[1](2, 2) = dev_rot * (inv_dt2);
    // deltaT
    _jacobianOplus[2](0, 0) = dev_x * (-acc.x() / dt->dt() - vel2.x() * inv_dt2);
    _jacobianOplus[2](1, 0) = dev_y * (-acc.y() / dt->dt() - vel2.y() * inv_dt2);
    _jacobianOplus[2](2, 0) = dev_rot * (-acc_rot / dt->dt() - omega2 * inv_dt2);
  }
#endif  // USE_ANALYTIC_JACOBI
  
  /**
   * @brief Set the initial velocity that is taken into account for calculating the acceleration
   * @param vel_start twist message containing the translational and rotational velocity
   */    
  void setInitialVelocity(const geometry_msgs::msg::Twist& vel_start)
  {
    _measurement = &vel_start;
  }  
      
  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};    

}; // end namespace

#endif /* EDGE_ACCELERATION_HOLONOMIC_START_H_ */