#ifndef EDGE_JERK_H
#define EDGE_JERK_H

#include "nav2_teb_controller/g2o_types/vertex_pose.h"
#include "nav2_teb_controller/g2o_types/vertex_timediff.h"
#include "nav2_teb_controller/g2o_types/base_teb_edges.h"
#include "nav2_teb_controller/g2o_types/penalties.h"
#include "nav2_teb_controller/g2o_types/edge_kinodynamics_helpers.hpp"
#include "nav2_teb_controller/core/pose_se2.hpp"
#include "nav2_teb_controller/math_utils.hpp"

#include <rclcpp/logging.hpp>
#include <geometry_msgs/msg/twist.hpp>
#include <angles/angles.h>
#include <exception>

// Generated by generate_parameter_library
#include "nav2_teb_controller/teb_controller_parameters.hpp"

namespace nav2_teb_controller
{ 
/*********************************************************************
 *
 * Wuhan University of Technology
 * 
 * School of Mechanical and Electrical Engineering
 * Author: Liu Rui
 * 

*********************************************************************/  
/**
 * @class EdgeJerk
 * @brief Edge defining the cost function for limiting the translational and rotational jerk.
 * 
 * The edge depends on seven vertices \f$ \mathbf{s}_i, \mathbf{s}_{i+1}, \mathbf{s}_{i+2}, \mathbf{s}_{i+3}, 
 * \Delta T_i, \Delta T_{i+1}, \Delta T_{i+2} \f$ and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [j, omegadotdot]^T ) \cdot weight \f$. \n
 * \e j is calculated using the difference quotient （thrice） and the position parts of four poses. \n
 * \e omegadotdot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi]. \n 
 * \e weight can be set using setInformation() \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval() \n
 * The dimension of the error / cost vector is 2: the first component represents the translational jerk and
 * the second one the rotational jerk
 * @see TebOptimalPlanner::AddEdgesJerk
 * @remarks Do not forget to call setTebConfig()
*/
class EdgeJerk : public BaseTebMultiEdge<2, double>
{
public:
  using BaseTebMultiEdge<2, double>::linearizeOplus;

  
  /**
   * @brief Construct edge
  */
  EdgeJerk()
  {
    this->resize(7);
  }

  /**
   * @brief Actual cost function
  */
  void computeError() override
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    // Get four poses and three deltaT
    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose3 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* pose4 = dynamic_cast<const VertexPose*>(_vertices[3]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[5]);
    const auto* dt3 = dynamic_cast<const VertexTimeDiff*>(_vertices[6]);

    // Using the difference quotient to calculate difference quotient
    const Eigen::Vector2d diff1 = pose2->position() - pose1->position();
    const Eigen::Vector2d diff2 = pose3->position() - pose2->position();
    const Eigen::Vector2d diff3 = pose4->position() - pose3->position();

    // Calculate the distance difference between poses
    double dist1 = diff1.norm();
    double dist2 = diff2.norm();
    double dist3 = diff3.norm();

    // Calculate the angle difference between poses
    const double angle_diff1 = angles::normalize_angle(pose2->theta() - pose1->theta());
    const double angle_diff2 = angles::normalize_angle(pose3->theta() - pose2->theta());
    const double angle_diff3 = angles::normalize_angle(pose4->theta() - pose3->theta());

    if (exact_arc_length) // use exact arc length instead of Euclidean approximation
    {
        if (angle_diff1 != 0)
        {
            const double radius = dist1 / (2 * sin(angle_diff1 / 2));
            dist1 = fabs(angle_diff1 * radius); // actual arg length!
        }
        if (angle_diff2 != 0)
        {
            const double radius = dist2 / (2 * sin(angle_diff2 / 2));
            dist2 = fabs(angle_diff2 * radius); // actual arg length!
        }
        if (angle_diff3 != 0)
        {
            const double radius = dist3 / (2 * sin(angle_diff3 / 2));
            dist3 = fabs(angle_diff3 * radius); // actual arg length!
        }
    }

    // LINEAR
    // Calculate the velocity
    double vel1 = dist1 / dt1->dt();
    double vel2 = dist2 / dt2->dt();
    double vel3 = dist3 / dt3->dt();

    // consider directions
    vel1 *= fast_sigmoid(100 * (diff1.x() * cos(pose1->theta()) + diff1.y() * sin(pose1->theta())));
    vel2 *= fast_sigmoid(100 * (diff2.x() * cos(pose2->theta()) + diff2.y() * sin(pose2->theta())));
    vel3 *= fast_sigmoid(100 * (diff3.x() * cos(pose3->theta()) + diff3.y() * sin(pose3->theta())));

    // Calculate the acceleration
    double acc_lin1 = (vel2 - vel1) * 2 / (dt1->dt() + dt2->dt());
    double acc_lin2 = (vel3 - vel2) * 2 / (dt2->dt() + dt3->dt());

    // Calculate and add the jerk
    const double jerk_lin = (acc_lin2 - acc_lin1) / ((dt1->dt() + dt2->dt()) / 4 + (dt2->dt() + dt3->dt()) / 4);

    _error[0] = penaltyBoundToInterval(jerk_lin, jerk_max_x, penalty_eps);

    // ANGULAR
    // Calculate the omega
    double omega1 = angle_diff1 / dt1->dt();
    double omega2 = angle_diff2 / dt2->dt();
    double omega3 = angle_diff3 / dt3->dt();

    // Calculate the acceleration
    double acc_rot1 = (omega2 - omega1) * 2 / (dt1->dt() + dt2->dt());
    double acc_rot2 = (omega3 - omega2) * 2 / (dt2->dt() + dt3->dt());

    // Calculate and add the jerk
    const double jerk_rot = (acc_rot2 - acc_rot1) / ((dt1->dt() + dt2->dt()) / 4 + (dt2->dt() + dt3->dt()) / 4);

    _error[1] = penaltyBoundToInterval(jerk_rot, jerk_max_theta, penalty_eps);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   *
   * Row 0: translational jerk, Row 1: rotational jerk. Reuses the
   * acceleration-pair partials of the shared kinodynamics helpers.
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose3 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* pose4 = dynamic_cast<const VertexPose*>(_vertices[3]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[5]);
    const auto* dt3 = dynamic_cast<const VertexTimeDiff*>(_vertices[6]);

    const SegmentMotion seg1 = makeSegmentMotion(
      pose2->position() - pose1->position(), pose1->theta(), pose2->theta(),
      dt1->dt(), exact_arc_length);
    const SegmentMotion seg2 = makeSegmentMotion(
      pose3->position() - pose2->position(), pose2->theta(), pose3->theta(),
      dt2->dt(), exact_arc_length);
    const SegmentMotion seg3 = makeSegmentMotion(
      pose4->position() - pose3->position(), pose3->theta(), pose4->theta(),
      dt3->dt(), exact_arc_length);
    const SigmoidTerm sig1 = makeSigmoidTerm(seg1.delta, seg1.cos_i, seg1.sin_i);
    const SigmoidTerm sig2 = makeSigmoidTerm(seg2.delta, seg2.cos_i, seg2.sin_i);
    const SigmoidTerm sig3 = makeSigmoidTerm(seg3.delta, seg3.cos_i, seg3.sin_i);

    const double vel1 = seg1.velRaw() * sig1.sigma;
    const double vel2 = seg2.velRaw() * sig2.sigma;
    const double vel3 = seg3.velRaw() * sig3.sigma;
    const double omega1 = seg1.omega();
    const double omega2 = seg2.omega();
    const double omega3 = seg3.omega();

    const AccelPairGrads pair1 = makeAccelPairGrads(
      seg1, sig1, vel1, omega1, seg2, sig2, vel2, omega2);
    const AccelPairGrads pair2 = makeAccelPairGrads(
      seg2, sig2, vel2, omega2, seg3, sig3, vel3, omega3);

    const double dt1v = dt1->dt();
    const double dt2v = dt2->dt();
    const double dt3v = dt3->dt();
    const double denom = (dt1v + 2.0 * dt2v + dt3v) / 4.0;
    const double jerk_lin = (pair2.a_lin - pair1.a_lin) / denom;
    const double jerk_rot = (pair2.a_rot - pair1.a_rot) / denom;

    const double dev_lin = penaltyBoundToIntervalDerivative(
      jerk_lin, jerk_max_x, penalty_eps);
    const double dev_rot = penaltyBoundToIntervalDerivative(
      jerk_rot, jerk_max_theta, penalty_eps);

    _jacobianOplus[0].setZero();
    _jacobianOplus[1].setZero();
    _jacobianOplus[2].setZero();
    _jacobianOplus[3].setZero();
    _jacobianOplus[4].setZero();
    _jacobianOplus[5].setZero();
    _jacobianOplus[6].setZero();

    // conf1
    _jacobianOplus[0].block<1, 3>(0, 0) =
      dev_lin * (-pair1.lin_pose[0].transpose()) / denom;
    _jacobianOplus[0].block<1, 3>(1, 0) =
      dev_rot * (-pair1.rot_pose[0].transpose()) / denom;
    // conf2
    _jacobianOplus[1].block<1, 3>(0, 0) =
      dev_lin * ((pair2.lin_pose[0] - pair1.lin_pose[1]).transpose()) / denom;
    _jacobianOplus[1].block<1, 3>(1, 0) =
      dev_rot * ((pair2.rot_pose[0] - pair1.rot_pose[1]).transpose()) / denom;
    // conf3
    _jacobianOplus[2].block<1, 3>(0, 0) =
      dev_lin * ((pair2.lin_pose[1] - pair1.lin_pose[2]).transpose()) / denom;
    _jacobianOplus[2].block<1, 3>(1, 0) =
      dev_rot * ((pair2.rot_pose[1] - pair1.rot_pose[2]).transpose()) / denom;
    // conf4
    _jacobianOplus[3].block<1, 3>(0, 0) =
      dev_lin * (pair2.lin_pose[2].transpose()) / denom;
    _jacobianOplus[3].block<1, 3>(1, 0) =
      dev_rot * (pair2.rot_pose[2].transpose()) / denom;
    // deltaT1
    _jacobianOplus[4](0, 0) = dev_lin *
      (-pair1.lin_dt[0] / denom - jerk_lin / (4.0 * denom));
    _jacobianOplus[4](1, 0) = dev_rot *
      (-pair1.rot_dt[0] / denom - jerk_rot / (4.0 * denom));
    // deltaT2
    _jacobianOplus[5](0, 0) = dev_lin *
      ((pair2.lin_dt[0] - pair1.lin_dt[1]) / denom - jerk_lin / (2.0 * denom));
    _jacobianOplus[5](1, 0) = dev_rot *
      ((pair2.rot_dt[0] - pair1.rot_dt[1]) / denom - jerk_rot / (2.0 * denom));
    // deltaT3
    _jacobianOplus[6](0, 0) = dev_lin *
      (pair2.lin_dt[1] / denom - jerk_lin / (4.0 * denom));
    _jacobianOplus[6](1, 0) = dev_rot *
      (pair2.rot_dt[1] / denom - jerk_rot / (4.0 * denom));
  }
#endif  // USE_ANALYTIC_JACOBI


  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};
    
/**
 * @class EdgeJerkStart
 * @brief Edge difining the cost function for limiting the translational and rotational jerk at the beginning of the trajectory.
 * 
 * The edge depends on five vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \mathbf{s}_{ip2}, \Delta T_i \f$, \Delta T_{i+1} \f$ 
 * an initial acceleration defined by setInitialAcceleration() and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [j, omegadotdot ]^T ) \cdot weight \f$. \n
 * \e j is calculated using the difference quotient (thrice) and the position parts of the poses. \n
 * \e omegadotdot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi].  \n
 * \e weight can be set using setInformation(). \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval(). \n
 * The dimension of the error / cost vector is 2: the first component represents the translational jerk and
 * the second one the rotational jerk.
 * @see TebOptimalPlanner::AddEdgesJerk
 * @see EdgeJerk
 * @see EdgeJerkGoal
 * @remarks Do not forget to call setTebConfig()
 * @remarks Refer to EdgeAccelerationGoal() for defining boundary values at the end of the trajectory!
*/
class EdgeJerkStart : public BaseTebMultiEdge<2, const geometry_msgs::msg::Twist*>
{
public:

  /**
   * @brief Constuct edge.
  */
  EdgeJerkStart()
  {
    _measurement = nullptr;
    this->resize(5);
  }
    
  /**
   * @brief Actual cost function
  */
  void computeError() override
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    // Obtain pose and time difference information from vertices
    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose3 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    // Calculate the distance difference and angle difference between poses
    const Eigen::Vector2d diff1 = pose2->position() - pose1->position();
    const Eigen::Vector2d diff2 = pose3->position() - pose2->position();
    double dist1 = diff1.norm();
    double dist2 = diff2.norm();
    const double angle_diff1 = angles::normalize_angle(pose2->theta() - pose1->theta());
    const double angle_diff2 = angles::normalize_angle(pose3->theta() - pose2->theta());

    if (exact_arc_length) // use exact arc length instead of Euclidean approximation
    {
        if (angle_diff1 != 0)
        {
            const double radius =  dist1/(2*sin(angle_diff1/2));
            dist1 = fabs( angle_diff1 * radius ); // actual arg length!
        }
        if (angle_diff2 != 0)
        {
            const double radius =  dist2/(2*sin(angle_diff2/2));
            dist2 = fabs( angle_diff2 * radius ); // actual arg length!
        }
    }
    
    // LINEAR
    // Calculate the velocity
    const double vel0 = _measurement->linear.x;
    double vel1 = dist1 / dt1->dt();
    double vel2 = dist2 / dt2->dt();

    // consider directions
    vel1 *= fast_sigmoid(100 * (diff1.x() * cos(pose1->theta()) + diff1.y() * sin(pose1->theta())));
    vel2 *= fast_sigmoid(100 * (diff2.x() * cos(pose2->theta()) + diff2.y() * sin(pose2->theta())));

    // Calculate the acceleration
    double acc_lin0 = (vel1 - vel0) / dt1->dt();
    double acc_lin1 = (vel2 - vel1) * 2 / (dt1->dt() + dt2->dt());

    // Calculate and add the jerk
    const double jerk_lin = (acc_lin1 - acc_lin0) / (dt1->dt() / 2 + (dt1->dt() + dt2->dt()) / 4);

    _error[0] = penaltyBoundToInterval(jerk_lin, jerk_max_x, penalty_eps);

    // ANGULAR
    // Calculate the omega
    const double omega0 = _measurement->angular.z;
    double omega1 = angle_diff1 / dt1->dt();
    double omega2 = angle_diff2 / dt2->dt();

    // Calculate the acceleration
    double acc_rot0 = (omega1 - omega0) / dt1->dt();
    double acc_rot1 = (omega2 - omega1) * 2 / (dt1->dt() + dt2->dt());

    // Calculate and add the jerk
    const double jerk_rot = (acc_rot1 - acc_rot0) / (dt1->dt() / 2 + (dt1->dt() + dt2->dt()) / 4);

    _error[1] = penaltyBoundToInterval(jerk_rot, jerk_max_theta, penalty_eps);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose3 = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    const SegmentMotion seg1 = makeSegmentMotion(
      pose2->position() - pose1->position(), pose1->theta(), pose2->theta(),
      dt1->dt(), exact_arc_length);
    const SegmentMotion seg2 = makeSegmentMotion(
      pose3->position() - pose2->position(), pose2->theta(), pose3->theta(),
      dt2->dt(), exact_arc_length);
    const SigmoidTerm sig1 = makeSigmoidTerm(seg1.delta, seg1.cos_i, seg1.sin_i);
    const SigmoidTerm sig2 = makeSigmoidTerm(seg2.delta, seg2.cos_i, seg2.sin_i);

    const double vel0 = _measurement->linear.x;
    const double vel1 = seg1.velRaw() * sig1.sigma;
    const double vel2 = seg2.velRaw() * sig2.sigma;
    const double omega0 = _measurement->angular.z;
    const double omega1 = seg1.omega();
    const double omega2 = seg2.omega();

    // initial acceleration (from the measured initial velocity)
    const double dt1v = dt1->dt();
    const double acc0_lin = (vel1 - vel0) / dt1v;
    const double acc0_rot = (omega1 - omega0) / dt1v;
    const double dvel1_dtheta1 =
      seg1.velRaw() * sig1.deriv * sig1.rot1 - sig1.sigma * seg1.d0 * seg1.dh_da / dt1v;
    const double dvel1_dtheta2 = sig1.sigma * seg1.d0 * seg1.dh_da / dt1v;

    // acceleration over the two segments
    const AccelPairGrads pair = makeAccelPairGrads(
      seg1, sig1, vel1, omega1, seg2, sig2, vel2, omega2);

    const double dt2v = dt2->dt();
    const double denom = dt1v / 2.0 + (dt1v + dt2v) / 4.0;
    const double jerk_lin = (pair.a_lin - acc0_lin) / denom;
    const double jerk_rot = (pair.a_rot - acc0_rot) / denom;

    const double dev_lin = penaltyBoundToIntervalDerivative(
      jerk_lin, jerk_max_x, penalty_eps);
    const double dev_rot = penaltyBoundToIntervalDerivative(
      jerk_rot, jerk_max_theta, penalty_eps);

    const double inv_dt1_2 = 1.0 / (dt1v * dt1v);

    _jacobianOplus[0].setZero();
    _jacobianOplus[1].setZero();
    _jacobianOplus[2].setZero();
    _jacobianOplus[3].setZero();
    _jacobianOplus[4].setZero();

    // conf1
    _jacobianOplus[0](0, 0) = dev_lin * (-sig1.sigma * seg1.arc * seg1.unit().x() * inv_dt1_2 / denom);
    _jacobianOplus[0](0, 1) = dev_lin * (-sig1.sigma * seg1.arc * seg1.unit().y() * inv_dt1_2 / denom);
    _jacobianOplus[0](0, 2) = dev_lin * (pair.lin_pose[0].z() - (-dvel1_dtheta1 / dt1v)) / denom;
    _jacobianOplus[0](1, 2) = dev_rot * (pair.rot_pose[0].z() - inv_dt1_2) / denom;
    // conf2
    _jacobianOplus[1].block<1, 2>(0, 0) = dev_lin *
      ((pair.lin_pose[1].head<2>() + sig1.sigma * seg1.arc * seg1.unit() * inv_dt1_2).transpose()) / denom;
    _jacobianOplus[1](0, 2) = dev_lin * (pair.lin_pose[1].z() - (-dvel1_dtheta2 / dt1v)) / denom;
    _jacobianOplus[1](1, 2) = dev_rot * (pair.rot_pose[1].z() + inv_dt1_2) / denom;
    // conf3
    _jacobianOplus[2].block<1, 3>(0, 0) = dev_lin * (pair.lin_pose[2].transpose()) / denom;
    _jacobianOplus[2].block<1, 3>(1, 0) = dev_rot * (pair.rot_pose[2].transpose()) / denom;
    // deltaT1
    _jacobianOplus[3](0, 0) = dev_lin *
      ((pair.lin_dt[0] - (-acc0_lin / dt1v - vel1 * inv_dt1_2)) / denom -
       jerk_lin * (3.0 / 4.0) / denom);
    _jacobianOplus[3](1, 0) = dev_rot *
      ((pair.rot_dt[0] - (-acc0_rot / dt1v - omega1 * inv_dt1_2)) / denom -
       jerk_rot * (3.0 / 4.0) / denom);
    // deltaT2
    _jacobianOplus[4](0, 0) = dev_lin *
      (pair.lin_dt[1] / denom - jerk_lin * (1.0 / 4.0) / denom);
    _jacobianOplus[4](1, 0) = dev_rot *
      (pair.rot_dt[1] / denom - jerk_rot * (1.0 / 4.0) / denom);
  }
#endif  // USE_ANALYTIC_JACOBI

  /**
   * @brief Set the initial velocity that is taken into account for calculating the acceleration
   * and use this speed to initialize the initial acceleration for the next step
   * @param vel_start twist message containing the translational and rotational velocity
   */    
  void setInitialVelocity(const geometry_msgs::msg::Twist& vel_start)
  {
    _measurement = &vel_start;
  }
  

  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};
    
/**
 * @class EdgeJerkGoal
 * @brief Edge difining the cost function for limiting the translational and rotational jerk at the end of the trajectory.
 * 
 * The edge depends on five vertices \f$ \mathbf{s}_i, \mathbf{s}_{ip1}, \mathbf{s}_{ip2}, \Delta T_i \f$, \Delta T_{i+1} \f$ 
 * an initial acceleration defined by setGoalAcceleration() and minimizes: \n
 * \f$ \min \textrm{penaltyInterval}( [j, omegadotdot ]^T ) \cdot weight \f$. \n
 * \e j is calculated using the difference quotient (thrice) and the position parts of the poses. \n
 * \e omegadotdot is calculated using the difference quotient of the yaw angles followed by a normalization to [-pi, pi].  \n
 * \e weight can be set using setInformation(). \n
 * \e penaltyInterval denotes the penalty function, see penaltyBoundToInterval(). \n
 * The dimension of the error / cost vector is 2: the first component represents the translational jerk and
 * the second one the rotational jerk.
 * @see TebOptimalPlanner::AddEdgesJerk
 * @see EdgeJerk
 * @see EdgeJerkGoal
 * @remarks Do not forget to call setTebConfig()
 * @remarks Refer to EdgeAccelerationGoal() for defining boundary values at the end of the trajectory!
*/
class EdgeJerkGoal : public BaseTebMultiEdge<2, const geometry_msgs::msg::Twist*>
{
public:

  /**
   * @brief Constuct edge.
  */
  EdgeJerkGoal()
  {
    _measurement = nullptr;
    this->resize(5);
  }
    
  /**
   * @brief Actual cost function
  */
  void computeError() override
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    // Obtain pose and time difference information from vertices
    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose_goal = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    // Calculate the distance difference and angle difference between poses
    const Eigen::Vector2d diff1 = pose2->position() - pose1->position();
    const Eigen::Vector2d diff2 = pose_goal->position() - pose2->position();
    double dist1 = diff1.norm();
    double dist2 = diff2.norm();
    const double angle_diff1 = angles::normalize_angle(pose2->theta() - pose1->theta());
    const double angle_diff2 = angles::normalize_angle(pose_goal->theta() - pose2->theta());

    if (exact_arc_length) // use exact arc length instead of Euclidean approximation
    {
        if (angle_diff1 != 0)
        {
            const double radius =  dist1/(2*sin(angle_diff1/2));
            dist1 = fabs( angle_diff1 * radius ); // actual arg length!
        }
        if (angle_diff2 != 0)
        {
            const double radius =  dist2/(2*sin(angle_diff2/2));
            dist2 = fabs( angle_diff2 * radius ); // actual arg length!
        }
    }
    
    // LINEAR
    // Calculate the velocity
    double vel1 = dist1 / dt1->dt();
    double vel2 = dist2 / dt2->dt();
    const double vel3 = _measurement->linear.x;

    // consider directions
    vel1 *= fast_sigmoid(100 * (diff1.x() * cos(pose1->theta()) + diff1.y() * sin(pose1->theta())));
    vel2 *= fast_sigmoid(100 * (diff2.x() * cos(pose2->theta()) + diff2.y() * sin(pose2->theta())));

    // Calculate the acceleration
    double acc_lin1 = (vel2 - vel1) * 2 / (dt1->dt() + dt2->dt());
    double acc_lin2 = (vel3 - vel2) / dt2->dt();

    // Calculate and add the jerk
    const double jerk_lin = (acc_lin2 - acc_lin1) / ((dt1->dt() + dt2->dt()) / 4 + dt2->dt() / 2);

    _error[0] = penaltyBoundToInterval(jerk_lin, jerk_max_x, penalty_eps);

    // ANGULAR
    // Calculate the omega
    double omega1 = angle_diff1 / dt1->dt();
    double omega2 = angle_diff2 / dt2->dt();
    const double omega3 = _measurement->angular.z;

    // Calculate the acceleration
    double acc_rot1 = (omega2 - omega1) * 2 / (dt1->dt() + dt2->dt());
    double acc_rot2 = (omega3 - omega2) / dt2->dt();

    // Calculate and add the jerk
    const double jerk_rot = (acc_rot2 - acc_rot1) / ((dt1->dt() + dt2->dt()) / 4 + dt2->dt() / 2);

    _error[1] = penaltyBoundToInterval(jerk_rot, jerk_max_theta, penalty_eps);
  }

  /**
   * @brief Jacobi matrix of the cost function specified in computeError().
   */
#if USE_ANALYTIC_JACOBI
  void linearizeOplus() override
  {
    // read params
    const double jerk_max_x = params_->FollowPath.robot.jerk_max_x;
    const double jerk_max_theta = params_->FollowPath.robot.jerk_max_theta;
    const double penalty_eps = params_->FollowPath.optimizer.penalty_epsilon;
    const bool exact_arc_length = params_->FollowPath.optimizer.exact_arc_length;

    const auto* pose1 = dynamic_cast<const VertexPose*>(_vertices[0]);
    const auto* pose2 = dynamic_cast<const VertexPose*>(_vertices[1]);
    const auto* pose_goal = dynamic_cast<const VertexPose*>(_vertices[2]);
    const auto* dt1 = dynamic_cast<const VertexTimeDiff*>(_vertices[3]);
    const auto* dt2 = dynamic_cast<const VertexTimeDiff*>(_vertices[4]);

    const SegmentMotion seg1 = makeSegmentMotion(
      pose2->position() - pose1->position(), pose1->theta(), pose2->theta(),
      dt1->dt(), exact_arc_length);
    const SegmentMotion seg2 = makeSegmentMotion(
      pose_goal->position() - pose2->position(), pose2->theta(), pose_goal->theta(),
      dt2->dt(), exact_arc_length);
    const SigmoidTerm sig1 = makeSigmoidTerm(seg1.delta, seg1.cos_i, seg1.sin_i);
    const SigmoidTerm sig2 = makeSigmoidTerm(seg2.delta, seg2.cos_i, seg2.sin_i);

    const double vel1 = seg1.velRaw() * sig1.sigma;
    const double vel2 = seg2.velRaw() * sig2.sigma;
    const double vel3 = _measurement->linear.x;
    const double omega1 = seg1.omega();
    const double omega2 = seg2.omega();
    const double omega3 = _measurement->angular.z;

    // final acceleration (towards the measured goal velocity)
    const double dt2v = dt2->dt();
    const double acc2_lin = (vel3 - vel2) / dt2v;
    const double acc2_rot = (omega3 - omega2) / dt2v;
    const double dvel2_dtheta2 =
      seg2.velRaw() * sig2.deriv * sig2.rot1 - sig2.sigma * seg2.d0 * seg2.dh_da / dt2v;
    const double dvel2_dtheta3 = sig2.sigma * seg2.d0 * seg2.dh_da / dt2v;

    // acceleration over the two segments
    const AccelPairGrads pair = makeAccelPairGrads(
      seg1, sig1, vel1, omega1, seg2, sig2, vel2, omega2);

    const double dt1v = dt1->dt();
    const double denom = (dt1v + dt2v) / 4.0 + dt2v / 2.0;
    const double jerk_lin = (acc2_lin - pair.a_lin) / denom;
    const double jerk_rot = (acc2_rot - pair.a_rot) / denom;

    const double dev_lin = penaltyBoundToIntervalDerivative(
      jerk_lin, jerk_max_x, penalty_eps);
    const double dev_rot = penaltyBoundToIntervalDerivative(
      jerk_rot, jerk_max_theta, penalty_eps);

    const double inv_dt2_2 = 1.0 / (dt2v * dt2v);

    _jacobianOplus[0].setZero();
    _jacobianOplus[1].setZero();
    _jacobianOplus[2].setZero();
    _jacobianOplus[3].setZero();
    _jacobianOplus[4].setZero();

    // conf1
    _jacobianOplus[0].block<1, 3>(0, 0) =
      dev_lin * (-pair.lin_pose[0].transpose()) / denom;
    _jacobianOplus[0].block<1, 3>(1, 0) =
      dev_rot * (-pair.rot_pose[0].transpose()) / denom;
    // conf2
    _jacobianOplus[1].block<1, 2>(0, 0) = dev_lin *
      ((sig2.sigma * seg2.arc * seg2.unit() * inv_dt2_2 - pair.lin_pose[1].head<2>()).transpose()) / denom;
    _jacobianOplus[1](0, 2) = dev_lin * ((-dvel2_dtheta2 / dt2v - pair.lin_pose[1].z()) / denom);
    _jacobianOplus[1](1, 2) = dev_rot * ((inv_dt2_2 - pair.rot_pose[1].z()) / denom);
    // goal pose
    _jacobianOplus[2].block<1, 2>(0, 0) = dev_lin *
      ((-sig2.sigma * seg2.arc * seg2.unit() * inv_dt2_2 - pair.lin_pose[2].head<2>()).transpose()) / denom;
    _jacobianOplus[2](0, 2) = dev_lin * ((-dvel2_dtheta3 / dt2v - pair.lin_pose[2].z()) / denom);
    _jacobianOplus[2](1, 2) = dev_rot * ((-inv_dt2_2 - pair.rot_pose[2].z()) / denom);
    // deltaT1
    _jacobianOplus[3](0, 0) = dev_lin *
      (-pair.lin_dt[0] / denom - jerk_lin * (1.0 / 4.0) / denom);
    _jacobianOplus[3](1, 0) = dev_rot *
      (-pair.rot_dt[0] / denom - jerk_rot * (1.0 / 4.0) / denom);
    // deltaT2
    _jacobianOplus[4](0, 0) = dev_lin *
      ((-acc2_lin / dt2v - vel2 * inv_dt2_2 - pair.lin_dt[1]) / denom -
       jerk_lin * (3.0 / 4.0) / denom);
    _jacobianOplus[4](1, 0) = dev_rot *
      ((-acc2_rot / dt2v - omega2 * inv_dt2_2 - pair.rot_dt[1]) / denom -
       jerk_rot * (3.0 / 4.0) / denom);
  }
#endif  // USE_ANALYTIC_JACOBI

  /**
   * @brief Set the goal / final velocity that is taken into account for calculating the acceleration
   * and use this speed to initialize the goal / final acceleration for the next step
   * @param vel_start twist message containing the translational and rotational velocity
   */    
  void setGoalVelocity(const geometry_msgs::msg::Twist& vel_start)
  {
    _measurement = &vel_start;
  }
  

  EIGEN_MAKE_ALIGNED_OPERATOR_NEW
};

} // end namespace

#endif